# -*- coding: utf-8 -*-
"""
ja-kanji-advanced（上級漢字コース）のうち、既存3コースの語彙に一切登場しない字の
使用例（実在する単語＋読み＋タガログ語訳）。kanji-example-words-generate Workflow
（生成→実在性検証の2段パイプライン）の出力から generate_manual_examples.py で
自動生成（手打ちではない）。
"""

MANUAL_EXAMPLES: dict[str, list[dict]] = {
    '浦': [{'headword': '津々浦々', 'reading': 'つつうらうら', 'gloss': 'sa buong bansa; sa bawat sulok ng bansa'}, {'headword': '浦島太郎', 'reading': 'うらしまたろう', 'gloss': 'pangunahing tauhan sa isang sikat na kuwentong-bayan ng Japan'}],
    '智': [{'headword': '智慧', 'reading': 'ちえ', 'gloss': 'karunungan (lalo na sa konteksto ng Budismo)'}],
    '弘': [{'headword': '弘法大師', 'reading': 'こうぼうだいし', 'gloss': 'dakilang paring Budista na si Kūkai, tagapagtatag ng Shingon Buddhism'}, {'headword': '弘前', 'reading': 'ひろさき', 'gloss': 'lungsod sa Aomori, Japan'}],
    '杉': [{'headword': '杉', 'reading': 'すぎ', 'gloss': 'punong sedar ng Japan'}, {'headword': '杉並', 'reading': 'すぎなみ', 'gloss': 'isang distrito sa Tokyo'}],
    '熊': [{'headword': '熊', 'reading': 'くま', 'gloss': 'oso'}, {'headword': '熊本', 'reading': 'くまもと', 'gloss': 'isang prefecture sa Kyushu, Japan'}],
    '彦': [{'headword': '彦星', 'reading': 'ひこぼし', 'gloss': 'ang bituing Altair, mula sa alamat ng Tanabata'}],
    '李': [{'headword': '李', 'reading': 'すもも', 'gloss': 'sirwelas (Japanese plum)'}],
    '浩': [{'headword': '浩然の気', 'reading': 'こうぜんのき', 'gloss': 'matapang at malawak na loob (mula sa pilosopiyang Tsino)'}],
    '宏': [{'headword': '宏大', 'reading': 'こうだい', 'gloss': 'napakalawak; malaki at malawak'}],
    '之': [{'headword': '龍之介', 'reading': 'りゅうのすけ', 'gloss': 'bahagi ng pangalan ng sikat na manunulat na si Akutagawa Ryūnosuke'}],
    '梨': [{'headword': '梨', 'reading': 'なし', 'gloss': 'peras (Japanese pear)'}, {'headword': '山梨', 'reading': 'やまなし', 'gloss': 'isang prefecture sa Japan'}],
    '鶴': [{'headword': '鶴', 'reading': 'つる', 'gloss': 'tagak'}, {'headword': '千羽鶴', 'reading': 'せんばづる', 'gloss': 'isang libong origami na tagak, simbolo ng mabuting kapalaran'}],
    '昌': [{'headword': '隆昌', 'reading': 'りゅうしょう', 'gloss': 'kasaganaan; pag-unlad'}],
    '貞': [{'headword': '貞操', 'reading': 'ていそう', 'gloss': 'kalinisang-puri; katapatan'}, {'headword': '貞淑', 'reading': 'ていしゅく', 'gloss': 'kahinhinan (ng babae)'}],
    '也': [{'headword': '拓也', 'reading': 'たくや', 'gloss': 'karaniwang pangalan ng lalaki sa Japan'}],
    '旭': [{'headword': '旭日', 'reading': 'きょくじつ', 'gloss': 'sumisikat na araw'}],
    '錦': [{'headword': '錦', 'reading': 'にしき', 'gloss': 'makulay na telang seda (brocade)'}, {'headword': '錦鯉', 'reading': 'にしきごい', 'gloss': 'koloreng koi (isda)'}],
    '磯': [{'headword': '磯', 'reading': 'いそ', 'gloss': 'baybaying puno ng bato'}, {'headword': '磯辺焼き', 'reading': 'いそべやき', 'gloss': 'inihaw na mochi na binalot ng nori'}],
    '駒': [{'headword': '駒', 'reading': 'こま', 'gloss': 'pyesa sa shogi'}],
    '聡': [{'headword': '聡明', 'reading': 'そうめい', 'gloss': 'matalino; matalas ang isip'}, {'headword': '聡い', 'reading': 'さとい', 'gloss': 'matalino; mabilis matuto'}],
    '曙': [{'headword': '曙', 'reading': 'あけぼの', 'gloss': 'bukang-liwayway'}],
    '萩': [{'headword': '萩', 'reading': 'はぎ', 'gloss': 'bulaklak na bush clover'}, {'headword': '萩市', 'reading': 'はぎし', 'gloss': 'lungsod sa Yamaguchi, Japan'}],
    '隻': [{'headword': '隻眼', 'reading': 'せきがん', 'gloss': 'may isang mata lang (bulag sa isang mata)'}],
    '栗': [{'headword': '栗', 'reading': 'くり', 'gloss': 'kastanyas'}, {'headword': '栗鼠', 'reading': 'りす', 'gloss': 'ardilya'}],
    '嘉': [{'headword': '嘉永', 'reading': 'かえい', 'gloss': 'pangalan ng isang panahon sa kasaysayan ng Japan (1848–1854)'}],
    '琴': [{'headword': '琴', 'reading': 'こと', 'gloss': 'koto (instrumentong kuwerdas ng Japan)'}, {'headword': '琴線', 'reading': 'きんせん', 'gloss': 'pinakamalalim na damdamin sa puso'}],
    '辰': [{'headword': '辰年', 'reading': 'たつどし', 'gloss': 'taon ng Dragon sa zodiac'}],
    '淳': [{'headword': '淳朴', 'reading': 'じゅんぼく', 'gloss': 'simple at tapat, likas na kabaitan'}],
    '鳩': [{'headword': '鳩', 'reading': 'はと', 'gloss': 'kalapati'}, {'headword': '鳩山', 'reading': 'はとやま', 'gloss': 'isang apelyidong Hapones (kilala dahil sa dating Punong Ministro)'}],
    '桂': [{'headword': '桂馬', 'reading': 'けいま', 'gloss': 'isang pyesa sa shogi (parang kabalyo sa chess)'}, {'headword': '桂', 'reading': 'かつら', 'gloss': 'puno ng katsura'}],
    '虎': [{'headword': '虎', 'reading': 'とら', 'gloss': 'tigre'}, {'headword': '虎の巻', 'reading': 'とらのまき', 'gloss': 'gabay o susi sa sagot (cheat sheet)'}],
    '晋': [{'headword': '東晋', 'reading': 'とうしん', 'gloss': 'isang dinastiyang Tsino (317–420 AD)'}],
    '晃': [{'headword': '晃', 'reading': 'あきら', 'gloss': 'karaniwang pangalan ng lalaki sa Japan'}],
    '桐': [{'headword': '桐', 'reading': 'きり', 'gloss': 'punong paulownia'}, {'headword': '桐箪笥', 'reading': 'きりだんす', 'gloss': 'aparador na gawa sa kahoy na paulownia'}],
    '鷹': [{'headword': '鷹', 'reading': 'たか', 'gloss': 'lawin'}, {'headword': '鷹匠', 'reading': 'たかじょう', 'gloss': 'tagapagsanay ng lawin (falconer)'}],
    '猪': [{'headword': '猪', 'reading': 'いのしし', 'gloss': 'baboy-ramo (wild boar)'}, {'headword': '猪突猛進', 'reading': 'ちょとつもうしん', 'gloss': 'pagmamadaling sumugod nang walang pag-iisip'}],
    '紘': [{'headword': '紘一', 'reading': 'こういち', 'gloss': 'karaniwang pangalan ng lalaki sa Japan'}],
    '庄': [{'headword': '庄屋', 'reading': 'しょうや', 'gloss': 'pinuno ng nayon noong panahon ng Edo'}, {'headword': '庄司', 'reading': 'しょうじ', 'gloss': 'isang apelyidong Hapones'}],
    '敦': [{'headword': '敦煌', 'reading': 'とんこう', 'gloss': 'Dunhuang, makasaysayang lungsod sa Tsina na bantog dahil sa mga kuweba ng Budda'}],
    '祐': [{'headword': '天祐', 'reading': 'てんゆう', 'gloss': 'tulong mula sa langit; magandang kapalaran'}],
    '鵬': [{'headword': '鵬程万里', 'reading': 'ほうていばんり', 'gloss': 'napakalayong paglalakbay; magandang kinabukasan (idyoma mula sa panitikang Tsino)'}],
    '亘': [{'headword': '亘る', 'reading': 'わたる', 'gloss': 'sumaklaw o umabot sa isang tagal ng panahon'}, {'headword': '亘理', 'reading': 'わたり', 'gloss': 'isang bayan sa Miyagi, Japan'}],
    '媛': [{'headword': '愛媛県', 'reading': 'えひめけん', 'gloss': 'isa sa mga prefecture sa Japan, nasa Shikoku'}],
    '恭': [{'headword': '恭しい', 'reading': 'うやうやしい', 'gloss': 'magalang; may paggalang'}],
    '笹': [{'headword': '笹', 'reading': 'ささ', 'gloss': 'kawayang-damo (bamboo grass)'}, {'headword': '笹舟', 'reading': 'ささぶね', 'gloss': 'munting bangkang gawa sa dahon ng kawayang-damo'}],
    '綾': [{'headword': '綾取り', 'reading': 'あやとり', 'gloss': "larong sinulid (cat's cradle)"}, {'headword': '綾', 'reading': 'あや', 'gloss': 'tela na may disenyong twill'}],
    '毅': [{'headword': '剛毅', 'reading': 'ごうき', 'gloss': 'matatag; matapang ang loob'}, {'headword': '毅然', 'reading': 'きぜん', 'gloss': 'matatag at hindi natitinag ang saloobin'}],
    '稔': [{'headword': '稔る', 'reading': 'みのる', 'gloss': 'mamunga; umani (matagumpay na resulta)'}, {'headword': '稔り', 'reading': 'みのり', 'gloss': 'ani; bunga ng pagsisikap'}],
    '駿': [{'headword': '駿馬', 'reading': 'しゅんめ', 'gloss': 'mabilis at magandang kabayo'}, {'headword': '駿河', 'reading': 'するが', 'gloss': 'lumang lalawigan, kasalukuyang bahagi ng Shizuoka'}],
    '亮': [{'headword': '亮', 'reading': 'りょう', 'gloss': 'karaniwang pangalan ng lalaki sa Japan'}],
    '坪': [{'headword': '坪', 'reading': 'つぼ', 'gloss': 'tsubo, yunit ng sukat ng lupa (humigit-kumulang 3.3 m²)'}, {'headword': '坪庭', 'reading': 'つぼにわ', 'gloss': 'maliit na hardin sa loob ng bahay (courtyard garden)'}],
    '椿': [{'headword': '椿', 'reading': 'つばき', 'gloss': 'kamelya (bulaklak)'}],
    '厘': [{'headword': '九分九厘', 'reading': 'くぶくりん', 'gloss': 'halos sigurado; 99 porsyento'}],
    '圭': [{'headword': '圭角', 'reading': 'けいかく', 'gloss': 'magaspang o matalas na ugali (gilid ng pagkatao)'}],
    '蓮': [{'headword': '蓮', 'reading': 'はす', 'gloss': 'lotus (bulaklak)'}, {'headword': '蓮根', 'reading': 'れんこん', 'gloss': 'ugat ng lotus (gulay)'}],
    '薫': [{'headword': '薫製', 'reading': 'くんせい', 'gloss': 'pinausukang pagkain'}, {'headword': '薫風', 'reading': 'くんぷう', 'gloss': 'mabangong hangin ng tag-init'}],
    '伍': [{'headword': '伍長', 'reading': 'ごちょう', 'gloss': 'kabo (ranggo sa militar)'}, {'headword': '落伍', 'reading': 'らくご', 'gloss': 'pagkahuli o pag-atras sa grupo'}],
    '斗': [{'headword': '北斗七星', 'reading': 'ほくとしちせい', 'gloss': 'Big Dipper (pangkat ng bituin)'}, {'headword': '漏斗', 'reading': 'ろうと', 'gloss': 'imbudo'}],
    '蘭': [{'headword': '蘭', 'reading': 'らん', 'gloss': 'orkidyas'}, {'headword': '蘭学', 'reading': 'らんがく', 'gloss': 'pag-aaral ng agham Kanluranin noong panahon ng Edo (mula Holland)'}],
    '秦': [{'headword': '秦', 'reading': 'はた', 'gloss': 'Hata (karaniwang apelyido ng Hapon)'}],
    '茅': [{'headword': '茅葺き', 'reading': 'かやぶき', 'gloss': 'bubong na dayami o kugon'}, {'headword': '茅ヶ崎', 'reading': 'ちがさき', 'gloss': 'Chigasaki (lungsod sa Japan)'}],
    '輔': [{'headword': '輔佐', 'reading': 'ほさ', 'gloss': 'katulong o tagapayo ng nakatataas'}],
    '嵐': [{'headword': '嵐', 'reading': 'あらし', 'gloss': 'bagyo'}, {'headword': '砂嵐', 'reading': 'すなあらし', 'gloss': 'bagyong buhangin'}],
    '郁': [{'headword': '馥郁', 'reading': 'ふくいく', 'gloss': 'mabango at masaganang amoy'}],
    '楠': [{'headword': '楠', 'reading': 'くすのき', 'gloss': 'puno ng kamper'}, {'headword': '楠木正成', 'reading': 'くすのきまさしげ', 'gloss': 'Kusunoki Masashige (makasaysayang heneral ng Japan)'}],
    '玲': [{'headword': '玲瓏', 'reading': 'れいろう', 'gloss': 'malinaw at magandang tunog o anyo (parang tunog ng hiyas)'}],
    '峠': [{'headword': '峠', 'reading': 'とうげ', 'gloss': 'pinakamataas na punto ng daan sa bundok; kasukdulan'}],
    '肇': [{'headword': '肇', 'reading': 'はじめ', 'gloss': "pangalan ng lalaki (nangangahulugang 'simula')"}],
    '亨': [{'headword': '亨', 'reading': 'とおる', 'gloss': 'pangalan ng lalaki'}],
    '逓': [{'headword': '逓信', 'reading': 'ていしん', 'gloss': 'komunikasyon (koreo/telekomunikasyon, lumang termino)'}, {'headword': '逓減', 'reading': 'ていげん', 'gloss': 'unti-unting pagbaba'}],
    '嶺': [{'headword': '高嶺の花', 'reading': 'たかねのはな', 'gloss': 'bagay na hindi maaabot o napakamahal (idyoma)'}, {'headword': '分水嶺', 'reading': 'ぶんすいれい', 'gloss': 'punto ng paghahati ng landas (watershed); mahalagang punto ng pagbabago'}],
    '喬': [{'headword': '喬木', 'reading': 'きょうぼく', 'gloss': 'puno (matangkad, di tulad ng palumpong)'}],
    '岬': [{'headword': '岬', 'reading': 'みさき', 'gloss': 'tangway; lupang nakausli sa dagat'}],
    '寅': [{'headword': '寅', 'reading': 'とら', 'gloss': 'Tigre (isa sa 12 hayop ng zodiac)'}, {'headword': '寅年', 'reading': 'とらどし', 'gloss': 'taon ng Tigre'}],
    '洲': [{'headword': '満洲', 'reading': 'まんしゅう', 'gloss': 'Manchuria (rehiyon sa Tsina)'}],
    '槙': [{'headword': '槙', 'reading': 'まき', 'gloss': 'puno ng maki (klase ng conifer sa Japan)'}],
    '巌': [{'headword': '巌流島', 'reading': 'がんりゅうじま', 'gloss': 'Isla Ganryū (makasaysayang lugar ng tunggalian)'}, {'headword': '巌', 'reading': 'いわお', 'gloss': 'malaking bato (matandang salita)'}],
    '峻': [{'headword': '峻険', 'reading': 'しゅんけん', 'gloss': 'matarik at mabatong (bundok)'}],
    '槻': [{'headword': '高槻', 'reading': 'たかつき', 'gloss': 'Takatsuki (lungsod sa Osaka, Japan)'}],
    '蝶': [{'headword': '蝶', 'reading': 'ちょう', 'gloss': 'paruparo'}, {'headword': '蝶々', 'reading': 'ちょうちょう', 'gloss': 'paruparo (magiliw na tawag)'}],
    '茎': [{'headword': '茎', 'reading': 'くき', 'gloss': 'tangkay'}, {'headword': '歯茎', 'reading': 'はぐき', 'gloss': 'gilagid'}],
    '蕉': [{'headword': '芭蕉', 'reading': 'ばしょう', 'gloss': 'puno ng saging; o makatang si Matsuo Bashō'}],
    '朋': [{'headword': '朋友', 'reading': 'ほうゆう', 'gloss': 'kaibigan (pormal na salita)'}],
    '藍': [{'headword': '藍', 'reading': 'あい', 'gloss': 'asul na tina (indigo)'}, {'headword': '藍色', 'reading': 'あいいろ', 'gloss': 'kulay indigo'}],
    '遼': [{'headword': '遼東半島', 'reading': 'りょうとうはんとう', 'gloss': 'Peninsula ng Liaodong (Tsina)'}],
    '孔': [{'headword': '孔子', 'reading': 'こうし', 'gloss': 'Confucius (dakilang pilosopo ng Tsina)'}, {'headword': '気孔', 'reading': 'きこう', 'gloss': 'maliit na butas sa dahon ng halaman (stoma)'}],
    '橘': [{'headword': '橘', 'reading': 'たちばな', 'gloss': 'tachibana (katutubong dalandan ng Japan); o apelyido'}],
    '漱': [{'headword': '夏目漱石', 'reading': 'なつめそうせき', 'gloss': 'Natsume Sōseki (bantog na manunulat ng Japan)'}],
    '巽': [{'headword': '巽', 'reading': 'たつみ', 'gloss': 'timog-silangan (lumang termino); o pangalan'}],
    '翁': [{'headword': '翁', 'reading': 'おきな', 'gloss': 'matandang lalaki (magalang na termino, ginagamit sa dulang Noh)'}],
    '瞳': [{'headword': '瞳', 'reading': 'ひとみ', 'gloss': 'balintataw ng mata; mata'}, {'headword': '瞳孔', 'reading': 'どうこう', 'gloss': 'balintataw (terminong medikal)'}],
    '欣': [{'headword': '欣喜雀躍', 'reading': 'きんきじゃくやく', 'gloss': 'lumukso sa matinding tuwa (idyoma)'}],
    '升': [{'headword': '升', 'reading': 'ます', 'gloss': 'kahong panukat (tradisyonal)'}, {'headword': '一升瓶', 'reading': 'いっしょうびん', 'gloss': 'bote ng sake (1.8 litro)'}],
    '巴': [{'headword': '巴', 'reading': 'ともえ', 'gloss': 'disenyong tomoe (hugis kuwit, tradisyonal sa Japan)'}, {'headword': '三つ巴', 'reading': 'みつどもえ', 'gloss': 'tatlong-panig na tunggalian (idyoma)'}],
    '禎': [{'headword': '禎子', 'reading': 'ていこ', 'gloss': 'pangalan ng babae (nangangahulugang mapalad)'}],
    '稜': [{'headword': '稜線', 'reading': 'りょうせん', 'gloss': 'linya ng rurok ng bundok (ridge line)'}],
    '倭': [{'headword': '倭国', 'reading': 'わこく', 'gloss': 'sinaunang tawag sa bansang Japan (ginamit ng Tsina)'}],
    '某': [{'headword': '某氏', 'reading': 'ぼうし', 'gloss': 'si Ginoong Fulano (hindi nagpapakilala ng tunay na pangalan)'}],
    '魁': [{'headword': '魁', 'reading': 'さきがけ', 'gloss': 'pasimuno; unang kumilos'}],
    '虹': [{'headword': '虹', 'reading': 'にじ', 'gloss': 'bahaghari'}],
    '鴻': [{'headword': '鴻鵠の志', 'reading': 'こうこくのこころざし', 'gloss': 'matayog na pangarap o hangarin (idyoma)'}],
    '赳': [{'headword': '赳夫', 'reading': 'たけお', 'gloss': 'pangalan ng lalaki (hal. dating Punong Ministro na si Fukuda Takeo)'}],
    '孟': [{'headword': '孟子', 'reading': 'もうし', 'gloss': 'Mencius; ang aklat ni Mencius (sinaunang pilosopong Tsino, tagasunod ni Confucius)'}, {'headword': '孟春', 'reading': 'もうしゅん', 'gloss': 'unang buwan ng tagsibol (klasikal na termino sa lunar calendar)'}],
    '尭': [{'headword': '尭舜', 'reading': 'ぎょうしゅん', 'gloss': 'Yao at Shun (alamat na mabubuting hari sa sinaunang Tsina, simbolo ng mahusay na pamamahala)'}],
    '巳': [{'headword': '巳年', 'reading': 'みどし', 'gloss': 'taon ng Ahas (sa animal zodiac ng Tsina)'}, {'headword': '上巳', 'reading': 'じょうし', 'gloss': 'ikatlong araw ng ikatlong buwan (klasikal na pista, pinagmulan ng Hina Matsuri)'}],
    '勅': [{'headword': '勅令', 'reading': 'ちょくれい', 'gloss': 'utos o dekreto ng emperador'}, {'headword': '勅使', 'reading': 'ちょくし', 'gloss': 'sugo o kinatawan ng emperador'}],
    '芹': [{'headword': '芹', 'reading': 'せり', 'gloss': "seri (isang gulay na ginagamit sa lutuing Hapon, kabilang sa 'pitong damo ng tagsibol')"}],
    '杏': [{'headword': '杏', 'reading': 'あんず', 'gloss': 'aprikot'}, {'headword': '杏仁豆腐', 'reading': 'あんにんどうふ', 'gloss': 'annindoufu (matamis na Tsino na gawa sa buto ng aprikot at gatas)'}],
    '鳳': [{'headword': '鳳凰', 'reading': 'ほうおう', 'gloss': 'Phoenix (alamat na ibon sa mitolohiyang Tsino, simbolo ng kadakilaan)'}],
    '馨': [{'headword': '馨しい', 'reading': 'かんばしい', 'gloss': 'mabango; kaaya-aya (amoy o reputasyon)'}],
    '慧': [{'headword': '智慧', 'reading': 'ちえ', 'gloss': 'karunungan (terminong Budismo)'}, {'headword': '慧眼', 'reading': 'けいがん', 'gloss': 'matalas na pananaw; kakayahang makakita ng katotohanan'}],
    '彬': [{'headword': '文質彬彬', 'reading': 'ぶんしつひんぴん', 'gloss': 'magkatimbang ang panloob na katangian at panlabas na anyo (kasabihang Tsino mula kay Confucius)'}],
    '匡': [{'headword': '匡正', 'reading': 'きょうせい', 'gloss': 'pagwawasto; pagtutuwid ng mali'}],
    '欽': [{'headword': '欽定', 'reading': 'きんてい', 'gloss': 'opisyal na pinagtibay ng emperador (hal. 欽定訳聖書 = King James Bible)'}],
    '嵯': [{'headword': '嵯峨', 'reading': 'さが', 'gloss': 'Saga (lugar sa Kyoto; pangalan din ng isang emperador, si Emperador Saga)'}],
    '綜': [{'headword': '綜絖', 'reading': 'そうこう', 'gloss': 'heddle (bahagi ng makinang panghabi ng tela)'}],
    '翠': [{'headword': '翡翠', 'reading': 'ひすい', 'gloss': 'jade (mamahaling batong hiyas na kadalasang kulay-berde)'}],
    '鮎': [{'headword': '鮎', 'reading': 'あゆ', 'gloss': 'ayu (isang uri ng isda sa tubig-tabang, sikat sa Japan)'}],
    '榛': [{'headword': '榛の木', 'reading': 'はんのき', 'gloss': 'puno ng alder (uri ng punongkahoy)'}, {'headword': '榛名山', 'reading': 'はるなさん', 'gloss': 'Mount Haruna (bulkan sa Gunma, Japan)'}],
    '蔦': [{'headword': '蔦', 'reading': 'つた', 'gloss': 'baging; ivy (halamang gumagapang)'}],
    '隼': [{'headword': '隼', 'reading': 'はやぶさ', 'gloss': 'peregrine falcon (mabilis na ibong mandaragit); ginamit ding pangalan ng spacecraft ng Japan'}],
    '渚': [{'headword': '渚', 'reading': 'なぎさ', 'gloss': 'baybayin; dalampasigan (patulang salita)'}],
    '稀': [{'headword': '稀少', 'reading': 'きしょう', 'gloss': 'napakabihira; kakaunti'}, {'headword': '古稀', 'reading': 'こき', 'gloss': 'ika-70 na kaarawan (tradisyonal na pagdiriwang)'}],
    '芙': [{'headword': '芙蓉', 'reading': 'ふよう', 'gloss': 'fuyo (uri ng bulaklak na hibiscus)'}],
    '皐': [{'headword': '皐月', 'reading': 'さつき', 'gloss': 'lumang pangalan ng Mayo (lunar calendar); uri rin ng bulaklak na azalea'}],
    '雛': [{'headword': '雛祭り', 'reading': 'ひなまつり', 'gloss': 'Hina Matsuri (pista ng mga batang babae, Marso 3)'}, {'headword': '雛人形', 'reading': 'ひなにんぎょう', 'gloss': 'manikang Hina, ipinapakita tuwing Hina Matsuri'}],
    '惟': [{'headword': '思惟', 'reading': 'しゆい', 'gloss': 'pagninilay; malalim na pag-iisip (terminong Budismo/pilosopiya)'}],
    '佑': [{'headword': '天佑', 'reading': 'てんゆう', 'gloss': 'tulong o pagpapala mula sa langit'}],
    '耀': [{'headword': '栄耀栄華', 'reading': 'えいようえいが', 'gloss': 'matinding karangyaan at kasaganaan (idiyoma)'}],
    '黛': [{'headword': '黛', 'reading': 'まゆずみ', 'gloss': 'itim na pinturang panlapat sa kilay (tradisyonal na kosmetiko)'}],
    '渥': [{'headword': '渥美半島', 'reading': 'あつみはんとう', 'gloss': 'Atsumi Peninsula (tangway sa Aichi, Japan)'}],
    '惇': [{'headword': '惇', 'reading': 'あつし', 'gloss': 'karaniwang pangalang lalaki sa Japan, nangangahulugang tapat o matapat'}],
    '脩': [{'headword': '束脩', 'reading': 'そくしゅう', 'gloss': 'regalong dinadala ng estudyante sa guro bilang simula ng pag-aaral (klasikal na termino mula kay Confucius)'}],
    '甫': [{'headword': '杜甫', 'reading': 'とほ', 'gloss': 'Du Fu (tanyag na makatang Tsino noong Tang Dynasty)'}],
    '蒼': [{'headword': '蒼白', 'reading': 'そうはく', 'gloss': 'maputla (kulay ng mukha dahil sa sakit o takot)'}],
    '暉': [{'headword': '落暉', 'reading': 'らっき', 'gloss': 'liwanag ng lumulubog na araw (patulang salita)'}],
    '只': [{'headword': '只今', 'reading': 'ただいま', 'gloss': "'nandito na ako' (bati pag-uwi sa bahay); o 'ngayon lang, kasalukuyan'"}],
    '檀': [{'headword': '檀家', 'reading': 'だんか', 'gloss': 'pamilyang tagasuporta ng templong Budista'}],
    '凱': [{'headword': '凱旋', 'reading': 'がいせん', 'gloss': 'matagumpay na pagbabalik (mula sa digmaan o kompetisyon)'}],
    '梓': [{'headword': '上梓', 'reading': 'じょうし', 'gloss': 'paglalathala ng aklat (klasikal/pormal na termino)'}],
    '丑': [{'headword': '丑年', 'reading': 'うしどし', 'gloss': 'taon ng Kalabaw (sa Chinese zodiac)'}, {'headword': '丑三つ時', 'reading': 'うしみつどき', 'gloss': 'kalagitnaan ng gabi, mga alas-2 hanggang 2:30 ng madaling-araw (ginagamit sa mga kuwentong multo)'}],
    '嗣': [{'headword': '皇嗣', 'reading': 'こうし', 'gloss': 'tagapagmana ng trono (Crown Prince)'}, {'headword': '嗣子', 'reading': 'しし', 'gloss': 'tagapagmana; anak na susunod sa pamilya'}],
    '汐': [{'headword': '汐留', 'reading': 'しおどめ', 'gloss': 'Shiodome (distrito ng negosyo sa Tokyo)'}],
    '絢': [{'headword': '絢爛', 'reading': 'けんらん', 'gloss': 'makinang at napakaganda; taos-pusong karangyaan'}],
    '朔': [{'headword': '朔日', 'reading': 'ついたち', 'gloss': 'unang araw ng buwan (sa lunar calendar)'}],
    '伽': [{'headword': 'お伽話', 'reading': 'おとぎばなし', 'gloss': 'kuwentong-bayan; fairy tale'}, {'headword': '伽藍', 'reading': 'がらん', 'gloss': 'kumplehong gusali ng templong Budista'}],
    '畝': [{'headword': '畝', 'reading': 'うね', 'gloss': 'hilera o guhit sa bukid para sa pagtatanim'}],
    '黎': [{'headword': '黎明', 'reading': 'れいめい', 'gloss': 'bukang-liwayway; simula ng bagong panahon'}],
    '壱': [{'headword': '壱岐', 'reading': 'いき', 'gloss': 'Iki (isla sa Nagasaki, Japan)'}],
    '允': [{'headword': '允恭天皇', 'reading': 'いんぎょうてんのう', 'gloss': 'Emperador Ingyō (ika-19 na emperador ng sinaunang Japan)'}],
    '鯉': [{'headword': '鯉', 'reading': 'こい', 'gloss': 'koi; carp (isda)'}, {'headword': '鯉のぼり', 'reading': 'こいのぼり', 'gloss': "streamer na hugis-isda, itinataas tuwing Children's Day (Mayo 5)"}],
    '舜': [{'headword': '堯舜', 'reading': 'ぎょうしゅん', 'gloss': 'Yao at Shun (alamat na mabubuting hari sa sinaunang Tsina)'}],
    '瑛': [{'headword': '瑛太', 'reading': 'えいた', 'gloss': 'Eita (kilalang aktor na Hapones; ang 瑛 ay nangangahulugang ningning ng hiyas)'}],
    '彪': [{'headword': '彪', 'reading': 'たけし', 'gloss': 'Ginagamit bilang pangalan ng lalaki sa Japan; sumisimbolo sa guhit ng tigre / tapang.'}],
    '卯': [{'headword': '卯月', 'reading': 'うづき', 'gloss': 'Lumang tawag sa ika-apat na buwan (Abril) sa kalendaryong lunar.'}, {'headword': '卯年', 'reading': 'うどし', 'gloss': 'Taon ng Kuneho sa zodiac ng Tsina.'}],
    '茜': [{'headword': '茜色', 'reading': 'あかねいろ', 'gloss': 'Malalim na kulay pula-kahel, katulad ng kulay ng kalangitan sa paglubog ng araw.'}],
    '皓': [{'headword': '皓々', 'reading': 'こうこう', 'gloss': 'Maliwanag at nagniningning, hal. ang buwan sa gabi.'}],
    '洸': [{'headword': '洸', 'reading': 'こう', 'gloss': 'Pangalan ng lalaki sa Japan; nangangahulugang kumikinang na tubig.'}],
    '毬': [{'headword': '手毬', 'reading': 'てまり', 'gloss': 'Tradisyunal na bolang gawa sa sinulid, ginagamit sa paglalaro.'}],
    '緋': [{'headword': '緋色', 'reading': 'ひいろ', 'gloss': 'Matingkad na pulang kulay (scarlet).'}, {'headword': '緋鯉', 'reading': 'ひごい', 'gloss': 'Pulang isdang koi.'}],
    '鯛': [{'headword': '鯛', 'reading': 'たい', 'gloss': 'Isdang tai / sea bream.'}, {'headword': '鯛焼き', 'reading': 'たいやき', 'gloss': 'Matamis na tinapay o keyk na hugis-isda, karaniwang may palamang matamis na munggo (red bean paste).'}],
    '怜': [{'headword': '怜悧', 'reading': 'れいり', 'gloss': 'Matalino at mabilis mag-isip.'}],
    '邑': [{'headword': '邑南町', 'reading': 'おおなんちょう', 'gloss': 'Isang bayan sa Shimane Prefecture, Japan.'}],
    '碧': [{'headword': '碧眼', 'reading': 'へきがん', 'gloss': 'Asul na mata.'}, {'headword': '紺碧', 'reading': 'こんぺき', 'gloss': 'Malalim na asul, gaya ng dagat o kalangitan.'}],
    '啄': [{'headword': '啄木鳥', 'reading': 'きつつき', 'gloss': 'Ibong tumutuka sa puno (woodpecker).'}],
    '穣': [{'headword': '豊穣', 'reading': 'ほうじょう', 'gloss': 'Masaganang ani.'}],
    '酉': [{'headword': '酉年', 'reading': 'とりどし', 'gloss': 'Taon ng Tandang sa zodiac ng Tsina.'}, {'headword': '酉の市', 'reading': 'とりのいち', 'gloss': 'Taunang pista-palengke sa Japan tuwing Nobyembre.'}],
    '悌': [{'headword': '孝悌', 'reading': 'こうてい', 'gloss': 'Paggalang sa magulang at nakatatanda; kilalang konsepto ni Confucius.'}],
    '繭': [{'headword': '繭', 'reading': 'まゆ', 'gloss': 'Balot na ginagawa ng uod (tulad ng silkworm) bago ito maging gamu-gamo; cocoon.'}],
    '颯': [{'headword': '颯爽', 'reading': 'さっそう', 'gloss': 'Matikas at masiglang anyo (dashing).'}],
    '諒': [{'headword': '諒解', 'reading': 'りょうかい', 'gloss': 'Pagkaunawa at pagsang-ayon.'}],
    '莉': [{'headword': '茉莉花', 'reading': 'まつりか', 'gloss': 'Sampagita / jasmine (bulaklak).'}],
    '栞': [{'headword': '栞', 'reading': 'しおり', 'gloss': 'Bookmark, pananda ng pahina ng libro.'}],
    '楓': [{'headword': '楓', 'reading': 'かえで', 'gloss': 'Puno ng maple.'}],
    '哉': [{'headword': '快哉', 'reading': 'かいさい', 'gloss': 'Sigaw ng tuwa o tagumpay.'}],
    '亥': [{'headword': '亥年', 'reading': 'いどし', 'gloss': 'Taon ng Baboy-ramo sa zodiac ng Tsina.'}],
    '胤': [{'headword': '落胤', 'reading': 'らくいん', 'gloss': 'Anak sa labas ng isang taong may mataas na katayuan.'}],
    '叡': [{'headword': '比叡山', 'reading': 'ひえいざん', 'gloss': 'Bundok Hiei, tanyag na banal na bundok malapit sa Kyoto.'}],
    '謁': [{'headword': '謁見', 'reading': 'えっけん', 'gloss': 'Pormal na pagharap o pakikipagkita sa hari o mataas na tao.'}],
    '茄': [{'headword': '茄子', 'reading': 'なす', 'gloss': 'Talong.'}],
    '侃': [{'headword': '侃侃諤諤', 'reading': 'かんかんがくがく', 'gloss': 'Bukas at masiglang pagtatalo kung saan lahat ay tapat magsalita.'}],
    '莞': [{'headword': '莞爾', 'reading': 'かんじ', 'gloss': 'Marahang pagngiti.'}],
    '誼': [{'headword': '友誼', 'reading': 'ゆうぎ', 'gloss': 'Matalik na pagkakaibigan, lalo na sa pagitan ng mga bansa.'}],
    '鞠': [{'headword': '蹴鞠', 'reading': 'けまり', 'gloss': 'Sinaunang larong Hapones na parang sipa-bola.'}],
    '斤': [{'headword': '一斤', 'reading': 'いっきん', 'gloss': 'Isang buong tinapay; yunit para sa pagbibilang ng tinapay.'}],
    '衿': [{'headword': '衿', 'reading': 'えり', 'gloss': 'Kwelyo ng damit.'}],
    '玖': [{'headword': '玖', 'reading': 'く', 'gloss': 'Opisyal/legal na anyo ng numerong siyam, ginagamit sa mga dokumento para maiwasan ang pandaraya.'}],
    '虞': [{'headword': '虞', 'reading': 'おそれ', 'gloss': 'Panganib o posibilidad ng masamang mangyayari (pormal na pananalita).'}],
    '袈': [{'headword': '袈裟', 'reading': 'けさ', 'gloss': 'Kesa, ang relihiyosong balabal ng monghe sa Budismo.'}],
    '絃': [{'headword': '管絃', 'reading': 'かんげん', 'gloss': 'Mga instrumentong hinihipan at may kwerdas; tumutukoy din sa klasikal na musikang Hapones na gumagamit ng mga ito.'}],
    '梧': [{'headword': '梧桐', 'reading': 'あおぎり', 'gloss': 'Puno ng parasol / Firmiana (uri ng punongkahoy).'}],
    '倖': [{'headword': '僥倖', 'reading': 'ぎょうこう', 'gloss': 'Hindi inaasahang suwerte.'}],
    '昂': [{'headword': '昂揚', 'reading': 'こうよう', 'gloss': 'Pagtaas ng diwa o sigla.'}],
    '瑳': [{'headword': '瑳', 'reading': 'さ', 'gloss': 'Kadalasang bahagi lamang ng pangalan ng tao sa Japan; bihira bilang karaniwang salita.'}],
    '裟': [{'headword': '袈裟', 'reading': 'けさ', 'gloss': 'Kesa, ang relihiyosong balabal ng monghe sa Budismo.'}],
    '采': [{'headword': '喝采', 'reading': 'かっさい', 'gloss': 'Palakpakan at papuri mula sa manonood.'}],
    '燦': [{'headword': '燦然', 'reading': 'さんぜん', 'gloss': 'Makinang at napakaganda; matingkad na liwanag.'}],
    '爾': [{'headword': '爾来', 'reading': 'じらい', 'gloss': 'Mula noon hanggang ngayon.'}],
    '紗': [{'headword': '更紗', 'reading': 'さらさ', 'gloss': 'Tela na may de-koloreng disenyo (chintz).'}],
    '勺': [{'headword': '一勺', 'reading': 'いっしゃく', 'gloss': 'Maliit na tradisyunal na yunit ng dami, humigit-kumulang 18ml.'}],
    '竣': [{'headword': '竣工', 'reading': 'しゅんこう', 'gloss': 'Pagkumpleto ng proyektong konstruksyon.'}],
    '恕': [{'headword': '寛恕', 'reading': 'かんじょ', 'gloss': 'Mapagpaumanhing kapatawaran (pormal na pananalita).'}],
    '捷': [{'headword': '敏捷', 'reading': 'びんしょう', 'gloss': 'Maliksi at mabilis kumilos.'}],
    '梢': [{'headword': '梢', 'reading': 'こずえ', 'gloss': 'Tuktok ng sanga ng puno (treetop).'}],
    '菖': [{'headword': '菖蒲', 'reading': 'しょうぶ', 'gloss': "iris (halaman); ginagamit sa paliguan tuwing Boys' Day (Tango no Sekku)"}],
    '丞': [{'headword': '丞相', 'reading': 'じょうしょう', 'gloss': 'punong ministro (titulo sa sinaunang Tsina/Hapon)'}],
    '錘': [{'headword': '紡錘', 'reading': 'ぼうすい', 'gloss': 'suliran; hugis-suliran (spindle), kasangkapan sa paghabi'}],
    '碩': [{'headword': '碩学', 'reading': 'せきがく', 'gloss': 'dakilang iskolar; taong may malalim na kaalaman'}],
    '朕': [{'headword': '朕', 'reading': 'ちん', 'gloss': 'ako (panghalip na ginagamit lamang ng emperador ng Hapon)'}],
    '紬': [{'headword': '紬', 'reading': 'つむぎ', 'gloss': 'tsumugi; uri ng habing seda'}],
    '凪': [{'headword': '凪', 'reading': 'なぎ', 'gloss': 'kalma (walang alon o hangin sa dagat)'}, {'headword': '夕凪', 'reading': 'ゆうなぎ', 'gloss': 'paghinto ng hangin sa dalampasigan tuwing takipsilim'}],
    '捺': [{'headword': '捺印', 'reading': 'なついん', 'gloss': 'pagpirma gamit ang selyo (hanko) sa dokumento'}],
    '弐': [{'headword': '弐', 'reading': 'に', 'gloss': "dalawa (pormal na anyo ng numerong '2', ginagamit sa legal/opisyal na dokumento)"}],
    '柊': [{'headword': '柊', 'reading': 'ひいらぎ', 'gloss': 'holly (puno); ginagamit bilang palamuti tuwing Setsubun'}],
    '蕗': [{'headword': '蕗', 'reading': 'ふき', 'gloss': 'fuki; halamang gulay na kinakain, kahawig ng rhubarb'}],
    '丙': [{'headword': '丙午', 'reading': 'ひのえうま', 'gloss': 'taon ng Apoy-Kabayo sa sinaunang kalendaryong Tsino (may kaugnay na pamahiin)'}, {'headword': '甲乙丙丁', 'reading': 'こうおつへいてい', 'gloss': 'una, ikalawa, ikatlo, ikaapat (paraan ng pagra-ranggo/grado)'}],
    '柾': [{'headword': '柾目', 'reading': 'まさめ', 'gloss': 'tuwid na guhit ng kahoy (straight grain), termino sa karpinterya'}],
    '亦': [{'headword': '亦', 'reading': 'また', 'gloss': 'din; muli (klasikal na anyo ng また)'}],
    '麿': [{'headword': '麿', 'reading': 'まろ', 'gloss': 'ako (sinaunang panghalip na ginamit ng mga maharlika noong Heian period)'}],
    '椋': [{'headword': '椋鳥', 'reading': 'むくどり', 'gloss': 'isang uri ng ibon (grey starling)'}],
    '匁': [{'headword': '匁', 'reading': 'もんめ', 'gloss': 'monme; sinaunang yunit ng bigat (3.75 gramo)'}],
    '冶': [{'headword': '鍛冶', 'reading': 'かじ', 'gloss': 'panday; paglalatero'}, {'headword': '冶金', 'reading': 'やきん', 'gloss': 'metalurhiya (agham ng paghahalo/pagproseso ng metal)'}],
    '耶': [{'headword': '有耶無耶', 'reading': 'うやむや', 'gloss': 'malabo; hindi malinaw ang kinahinatnan'}],
    '蓉': [{'headword': '芙蓉', 'reading': 'ふよう', 'gloss': 'isang uri ng bulaklak (cotton rose/hibiscus)'}],
    '琳': [{'headword': '琳派', 'reading': 'りんぱ', 'gloss': 'Rinpa; paaralan ng dekoratibong sining ng Hapon'}],
    '伶': [{'headword': '伶人', 'reading': 'れいじん', 'gloss': 'musikero sa sinaunang korte ng Hapon'}],
    '侑': [{'headword': '侑子', 'reading': 'ゆうこ', 'gloss': 'Yuuko (karaniwang babaeng pangalan sa Hapon)'}],
    '勁': [{'headword': '勁敵', 'reading': 'けいてき', 'gloss': 'matinding karibal; malakas na kalaban'}],
    '奎': [{'headword': '奎宿', 'reading': 'けいしゅく', 'gloss': 'isa sa 28 konstelasyon sa sinaunang astronomiyang Tsino, kaugnay ng panitikan'}],
    '崚': [{'headword': '崚嶒', 'reading': 'りょうそう', 'gloss': 'matarik at magkasunod-sunod na anyong bundok; ginagamit upang ilarawan ang mga bulubunduking lupain'}],
    '昴': [{'headword': '昴', 'reading': 'すばる', 'gloss': 'Pleiades; kumpol ng bituin (kilala rin bilang Subaru)'}],
    '晏': [{'headword': '晏子', 'reading': 'あんし', 'gloss': 'Yanzi; sikat na estadistang Tsino noong sinaunang panahon'}],
    '晨': [{'headword': '晨光', 'reading': 'しんこう', 'gloss': 'liwanag ng bukang-liwayway; unang sinag ng umaga'}],
    '晟': [{'headword': '晟', 'reading': 'あきら', 'gloss': "Akira (lalaking pangalan sa Hapon, mula sa kahulugang 'maliwanag/malinaw')"}],
    '椰': [{'headword': '椰子', 'reading': 'やし', 'gloss': 'puno ng niyog (coconut palm)'}],
    '洵': [{'headword': '洵に', 'reading': 'まことに', 'gloss': 'talaga; tunay (klasikal na pang-abay)'}],
    '滉': [{'headword': '滉', 'reading': 'こう', 'gloss': "Kou (lalaking pangalan sa Hapon, mula sa kahulugang 'malalim at malawak')"}],
    '澪': [{'headword': '澪標', 'reading': 'みおつくし', 'gloss': 'tanda ng daanan ng bapor sa tubig; sagisag ng Osaka, sikat sa Tale of Genji'}, {'headword': '澪', 'reading': 'みお', 'gloss': 'Mio (karaniwang babaeng pangalan sa Hapon)'}],
    '燎': [{'headword': '燎原の火', 'reading': 'りょうげんのひ', 'gloss': 'apoy sa parang na mabilis kumalat (matalinghagang parirala para sa mabilis na paglaganap)'}],
    '燿': [{'headword': '燿', 'reading': 'あきら', 'gloss': "Akira (lalaking pangalan sa Hapon, mula sa kahulugang 'nagniningning')"}],
    '瑶': [{'headword': '瑶子', 'reading': 'ようこ', 'gloss': 'Youko (karaniwang babaeng pangalan sa Hapon)'}],
    '眸': [{'headword': '眸', 'reading': 'ひとみ', 'gloss': 'mga mata (patula/pampanitikang salita)'}],
    '笙': [{'headword': '笙', 'reading': 'しょう', 'gloss': 'shō; tradisyunal na instrumentong hinihipan, ginagamit sa gagaku (sinaunang musikang pang-imperyal)'}],
    '綸': [{'headword': '経綸', 'reading': 'けいりん', 'gloss': 'pamamahala ng bansa; malawakang pagpaplano sa pamahalaan'}],
    '茉': [{'headword': '茉莉花', 'reading': 'まつりか', 'gloss': 'hasmin (bulaklak)'}],
    '菫': [{'headword': '菫', 'reading': 'すみれ', 'gloss': 'violeta (bulaklak); karaniwan ding babaeng pangalan'}],
    '詢': [{'headword': '諮詢', 'reading': 'しじゅん', 'gloss': 'pagkonsulta; paghingi ng payo (pormal/legal na termino)'}],
    '迪': [{'headword': '迪宮', 'reading': 'みちのみや', 'gloss': 'Michi-no-miya; titulo ni Emperador Showa noong bata pa (bago maging emperador)'}],
    '頌': [{'headword': '頌歌', 'reading': 'しょうか', 'gloss': 'awit ng papuri (hymn/ode)'}],
    '凜': [{'headword': '凜々しい', 'reading': 'りりしい', 'gloss': 'matapang at marangal ang itsura (gallant/dignified)'}],
    '熙': [{'headword': '康熙', 'reading': 'こうき', 'gloss': "Kangxi; panahon ng isang emperador ng Tsina, kilala rin sa 'Kangxi Dictionary', sikat na diksyunaryo ng kanji"}],
}
