# -*- coding: utf-8 -*-
"""
ja-kanji-advanced（上級漢字コース）の単字グロスのうち、既存3コースの単字見出しに
無かった字のタガログ語訳。kanji-tagalog-translate Workflow（翻訳→検証の2段パイプライン）
の出力から generate_manual_gloss.py で自動生成（手打ちではない）。
"""

MANUAL_GLOSS: dict[str, str] = {
    '取': 'kumuha; kunin',
    '付': 'dumikit; ikabit',
    '引': 'hilahin; banggitin',
    '定': 'magpasya; itakda',
    '当': 'tumama; nararapat',
    '化': 'magbago; maging',
    '込': 'masikip; kasali',
    '産': 'produkto; manganak',
    '成': 'maging; matupad',
    '務': 'tungkulin; trabaho',
    '受': 'tumanggap; sagutin',
    '感': 'damdamin; pakiramdam',
    '議': 'pulong; talakayan',
    '保': 'ingatan; panatilihin',
    '調': 'siyasatin; ihanda; himig',
    '打': 'hampasin; paluin',
    '連': 'isama; grupo',
    '最': 'pinaka-; higit sa lahat',
    '義': 'katarungan; kahulugan',
    '落': 'mahulog; bumagsak',
    '論': 'pangangatwiran; pagtatalo',
    '乗': 'sumakay; sumali',
    '官': 'opisyal; pamahalaan',
    '平': 'patag; kapayapaan',
    '交': 'makihalubilo; palitan',
    '記': 'isulat; talaan',
    '投': 'itapon; mamuhunan',
    '向': 'harapin; patungo sa',
    '進': 'sumulong; umunlad',
    '返': 'ibalik; sagutin',
    '配': 'ipamahagi; asawa',
    '過': 'sobra; lumampas',
    '解': 'unawain; kalasin',
    '好': 'gusto; magustuhan',
    '退': 'umatras; magretiro',
    '結': 'itali; magbuklod',
    '団': 'grupo; samahan',
    '然': 'gayon; talaga',
    '消': 'patayin; burahin',
    '放': 'palayain; ilabas',
    '算': 'magbilang; kalkulahin',
    '予': 'paunang; bago',
    '勝': 'manalo; tagumpay',
    '在': 'umiiral; matatagpuan',
    '満': 'puno; sapat',
    '収': 'kita; ipunin',
    '掛': 'isabit; umasa',
    '現': 'kasalukuyan; totoo',
    '士': 'propesyonal; mandirigma',
    '演': 'magtanghal; gumanap',
    '冷': 'malamig; palamigin',
    '失': 'mawala; pagkakamali',
    '速': 'mabilis; bilisan',
    '治': 'gumaling; mamahala',
    '伝': 'ipaabot; alamat',
    '寄': 'lumapit; mag-abuloy',
    '絶': 'putulin; lubos',
    '防': 'ipagtanggol; harangan',
    '養': 'alagaan; palakihin',
    '追': 'habulin; sundan',
    '価': 'halaga; presyo',
    '張': 'banatin; itayo',
    '路': 'daan; ruta',
    '給': 'sahod; ibigay',
    '老': 'matanda; tumanda',
    '資': 'puhunan; yaman',
    '減': 'kumulang; bumawas',
    '苦': 'paghihirap; pag-aalala',
    '告': 'sabihin; ipahayag',
    '限': 'limitasyon; hangganan',
    '検': 'suriin; siyasatin',
    '省': 'magnilay-nilay; ministri',
    '居': 'manirahan; naririto',
    '両': 'pareho; dalawa',
    '育': 'palakihin; lumaki',
    '続': 'ituloy; magpatuloy',
    '支': 'suportahan; sangay',
    '参': 'dumalo; sumali',
    '容': 'anyo; nilalaman; hitsura',
    '造': 'gumawa; likhain',
    '改': 'baguhin; ayusin',
    '応': 'sumagot; pumayag',
    '活': 'masigla; buhay',
    '増': 'dumami; dagdagan',
    '撃': 'atakihin; sumalakay',
    '営': 'magpatakbo ng negosyo; kampo',
    '接': 'makipag-ugnayan; dumikit',
    '師': 'guro; dalubhasa',
    '振': 'iwagayway; alugin',
    '散': 'kumalat; sabugin',
    '飛': 'lumipad; lumaktaw',
    '越': 'tumawid; lumagpas',
    '設': 'itatag; ihanda',
    '余': 'sobra; labis',
    '突': 'saksakin; biglaan',
    '殺': 'pumatay; puksain',
    '違': 'iba; kaiba',
    '洗': 'maghugas; linisin',
    '覚': 'tandaan; matuto; gumising',
    '渡': 'tumawid; ibigay; maghatid',
    '留': 'manatili; huminto; itigil',
    '異': 'iba; kakaiba',
    '視': 'tingnan; siyasatin; ituring',
    '示': 'ipakita; ituro',
    '置': 'ilagay; iwan; panatilihin',
    '降': 'bumaba; umulan; sumuko',
    '温': 'mainit-init; maligamgam',
    '盛': 'umunlad; sumikat; lumago',
    '修': 'mag-aral; sanayin; ayusin ang sarili',
    '衛': 'ipagtanggol; bantayan',
    '遺': 'ipamana; iwan',
    '短': 'maikli; kapintasan; kahinaan',
    '軽': 'magaan; hindi mahalaga',
    '細': 'manipis; makitid; detalyado',
    '辞': 'magbitiw; salita; termino',
    '果': 'bunga; matupad; matapos',
    '済': 'matapos; mabayaran; hindi na kailangan',
    '談': 'pag-usapan; kausapin',
    '競': 'makipagkumpitensya; makipagpaligsahan; magkarera',
    '婦': 'babae; asawang babae; babaing ikakasal',
    '護': 'protektahan; ipagsanggalang',
    '替': 'ipalit; kapalit; magpalit',
    '識': 'alamin; kilalanin; kaalaman',
    '領': 'teritoryo; nasasakupan',
    '装': 'magbihis; magkunwari',
    '処': 'asikasuhin; pangasiwaan; hatulan',
    '裁': 'humatol; magpasya; gupitin (tela)',
    '離': 'humiwalay; maghiwalay',
    '乱': 'kaguluhan; guluhin',
    '抜': 'bunutin; hugutin; alisin',
    '働': 'magtrabaho',
    '確': 'tiyakin; sigurado; matatag',
    '残': 'matira; natitira',
    '適': 'angkop; bagay; kwalipikado',
    '守': 'bantayan; ipagtanggol; sundin',
    '望': 'umasa; nais; hangarin',
    '隊': 'grupo; pangkat',
    '専': 'espesyalidad; eksklusibo; pangunahin',
    '圧': 'presyon; pigain; apihin',
    '遠': 'malayo',
    '勢': 'lakas; puwersa; sigla',
    '太': 'mataba; makapal',
    '締': 'higpitan; isara; itali',
    '認': 'kilalanin; aminin; paniwalaan',
    '査': 'imbestigahan; siyasatin',
    '健': 'malusog; malakas',
    '禁': 'ipagbawal; bawal',
    '挙': 'itaas; ihain; gawain',
    '低': 'mababa; mapagpakumbaba',
    '呼': 'tumawag; anyayahan',
    '除': 'alisin; ibukod; hatiin',
    '静': 'tahimik',
    '必': 'tiyak; siguradong mangyayari',
    '備': 'maghanda; ilaan; kagamitan',
    '払': 'magbayad; alisin',
    '射': 'bumaril; pumana; sumikat (liwanag)',
    '存': 'umiral; mayroon; ipagpalagay',
    '破': 'sirain; punitin; talunin',
    '清': 'malinis; linisin; dalisay',
    '達': 'makarating; maabot; matamo',
    '若': 'bata; baka (kung sakali)',
    '痛': 'masakit; sakit',
    '警': 'babalaan; kautusan',
    '準': 'semi-; katumbas; sumunod sa pamantayan',
    '深': 'malalim; palakasin',
    '規': 'pamantayan; tuntunin',
    '焼': 'ihawin; sunugin',
    '片': 'piraso; isang panig',
    '復': 'ibalik; bumalik; ipagpatuloy muli',
    '態': 'saloobin; kalagayan',
    '効': 'bisa; benepisyo; epekto',
    '疑': 'magduda; pagdudahan',
    '航': 'maglayag; lumipad',
    '材': 'materyales; kahoy; sangkap',
    '激': 'marahas; matindi; magalit nang husto',
    '栄': 'umunlad; karangalan; kaluwalhatian',
    '快': 'masaya; kaaya-aya; komportable',
    '縮': 'umurong; lumiit; kumupos',
    '暴': 'marahas; brutal; biglaang pagsabog ng galit',
    '押': 'itulak; pindutin; pigilan',
    '厚': 'makapal; mabait; magiliw',
    '察': 'hulaan; maunawaan; humatol',
    '敗': 'matalo; kabiguan',
    '倒': 'bumagsak; ibagsak; gumuho',
    '固': 'tumigas; mamuo; kumapal',
    '移': 'lumipat; ilipat',
    '換': 'ipalit; palitan; kumbertihin',
    '完': 'kumpleto; matapos',
    '協': 'makipagtulungan; sama-sama',
    '更': 'baguhin; higit pa; muli',
    '条': 'artikulo; sugnay; guhit',
    '補': 'dagdagan; punan; katulong',
    '免': 'patawarin; alisan ng pananagutan',
    '混': 'haluin; maghalo; malito',
    '浮': 'lumutang; pumaimbabaw',
    '構': 'itayo; bumuo; magkunwari',
    '遊': 'maglaro; magsaya; mamasyal',
    '登': 'umakyat; sumampa',
    '脱': 'maghubad; tumakas; makawala',
    '勤': 'magtrabaho; maglingkod; masipag',
    '争': 'makipagtalo; magkumpitensya; makipag-away',
    '険': 'mapanganib; matarik',
    '笑': 'tumawa; ngumiti',
    '障': 'hadlang; sagabal; balakid',
    '録': 'itala; talaan; rekord',
    '統': 'pamunuan; kaugnayan; kontrolin',
    '滅': 'mamatay; malipol; wasakin',
    '欠': 'kulang; kapintasan; hindi dumalo',
    '詰': 'siksikin; punuin; sisihin',
    '廃': 'alisin; ipawalang-bisa; itigil',
    '駆': 'tumakbo; sumugod; itaboy',
    '暗': 'madilim; kadiliman',
    '閉': 'isara; sarado',
    '介': 'mamagitan; tumulong; pamamagitan',
    '厳': 'mahigpit; istrikto; seryoso',
    '悲': 'malungkot; kalungkutan',
    '講': 'lektura; talakayin; asosasyon',
    '植': 'magtanim; itanim',
    '致': 'magdulot; magsanhi; gawin (magalang)',
    '企': 'magplano; balak; pagtatangka',
    '染': 'kulayan; magtina; mabahiran',
    '救': 'iligtas; sagipin; tulungan',
    '推': 'hulaan; ipalagay; irekomenda',
    '伸': 'umunat; humaba; lumago',
    '訴': 'magsakdal; umapela; magreklamo',
    '詞': 'salita; titik ng kanta',
    '継': 'ipagpatuloy; magmana; humalili',
    '皇': 'emperador',
    '称': 'tawag; titulo; papuri',
    '聴': 'makinig; pakinggan',
    '遅': 'mabagal; huli',
    '歴': 'kasaysayan; karanasan',
    '探': 'maghanap; hanapin',
    '典': 'alituntunin; batas; seremonya',
    '亡': 'yumao; namatay; patay na',
    '包': 'balutin; balot',
    '況': 'kalagayan; sitwasyon',
    '販': 'magbenta; ibenta',
    '府': 'pamahalaan; opisina ng gobyerno; prepektura',
    '域': 'rehiyon; saklaw; lawak',
    '提': 'magmungkahi; iharap; iprisenta',
    '爆': 'sumabog; bomba',
    '納': 'magbayad; itago; ihatid',
    '与': 'magbigay; ibigay; gawaran',
    '整': 'ayusin; maayos; ihanda',
    '属': 'kabilang; kasapi; sakop',
    '延': 'ipagpaliban; pahabain; palawigin',
    '創': 'lumikha; simulan; sugat',
    '司': 'mamahala; pinuno; opisyal',
    '即': 'agad; kaagad; ibig sabihin',
    '婚': 'kasal; pag-aasawa',
    '薄': 'manipis; malabnaw',
    '震': 'manginig; yumanig; lindol',
    '戻': 'bumalik; ibalik; isauli',
    '逃': 'tumakas; iwasan; tumalilis',
    '触': 'hipuin; dumampi; makipag-ugnayan',
    '訪': 'bumisita; dalawin',
    '似': 'kamukha; magkahawig; tumulad',
    '攻': 'sumalakay; umatake; punahin',
    '環': 'singsing; bilog; kadena',
    '責': 'sisihin; managot; pananagutan',
    '被': 'danasin; matamaan; sumailalim sa',
    '犯': 'krimen; gumawa ng krimen; kasalanan',
    '導': 'gabayan; pangunahan; giyahan',
    '標': 'marka; tanda; tunguhin',
    '互': "isa't isa; resiprokal; sabay-sabay",
    '求': 'humingi; hilingin; hanapin',
    '惑': 'malito; ligaligin; pagkalito',
    '築': 'magtayo; itayo; buuin',
    '恐': 'matakot; takot; kilabot',
    '請': 'humiling; makiusap; mag-imbita',
    '微': 'napakaliit; bahagya; banayad',
    '誤': 'mali; pagkakamali; magkamali',
    '華': 'kariktan; makinang; magarbo',
    '災': 'sakuna; kalamidad',
    '従': 'sumunod; sundin; tumalima',
    '占': 'sakupin; angkinin; manghula (ng kapalaran)',
    '遣': 'ipadala; magpadala',
    '照': 'magliwanag; ihambing; sumikat',
    '採': 'pumili; kumuha; mangalap',
    '刊': 'ilathala; maglathala',
    '闘': 'lumaban; away; digmaan',
    '償': 'magbayad-pinsala; bayaran; kabayaran',
    '宮': 'palasyo; dambana',
    '其': 'iyon; yaon',
    '授': 'magturo; ituro; gawaran',
    '辛': 'maanghang; mahirap tiisin',
    '汚': 'marumi; dumihan; kontaminado',
    '暖': 'mainit-init; init',
    '卒': 'magtapos (ng pag-aaral); sundalo',
    '季': 'panahon (ng taon)',
    '輸': 'ipadala; ihatid',
    '景': 'tanawin; eksena',
    '眠': 'matulog; antok',
    '捕': 'hulihin; dakpin',
    '担': 'pasanin; balikatin (responsibilidad)',
    '委': 'ipagkatiwala; komite',
    '均': 'pantay; katamtaman',
    '奏': 'tumugtog ng musika',
    '抗': 'lumaban; tumutol; sumalungat',
    '貴': 'mahalaga; marangal',
    '繰': 'balikan; ikutin; muling tingnan',
    '奇': 'kakaiba; kataka-taka',
    '診': 'magpasuri; suriin (ng doktor)',
    '層': 'saray; antas; palapag',
    '貨': 'kalakal; salapi',
    '敷': 'ilatag; ipatong',
    '執': 'hawakan; gampanan; isagawa',
    '葬': 'ilibing; libing',
    '序': 'paunang salita; pagkakasunod-sunod',
    '干': 'patuyuin; tumuyo',
    '却': 'sa halip; umatras',
    '閣': 'tore; palasyo',
    '託': 'ipagkatiwala; ipaubaya',
    '陣': 'kampo; hanay ng hukbo',
    '寒': 'malamig (panahon)',
    '危': 'mapanganib; delikado',
    '鳴': 'tumunog; humuni (ibon); tumahol (aso)',
    '易': 'madali; simple',
    '久': 'matagal na panahon',
    '祝': 'ipagdiwang; batiin',
    '慣': 'masanay; maging bihasa',
    '喜': 'matuwa; magalak',
    '迎': 'salubungin; batiin',
    '揺': 'umuga; yumanig',
    '飾': 'palamutihan; gayakan',
    '謝': 'humingi ng tawad; magpasalamat',
    '展': 'palawakin; ipakita (eksibit)',
    '覧': 'tingnan; basahin',
    '盗': 'magnakaw',
    '暮': 'takipsilim; mamuhay',
    '療': 'gamutin; pagalingin',
    '囲': 'palibutan; kulungin',
    '迷': 'maligaw; malito',
    '候': 'panahon; klima; hintayin',
    '模': 'tularan; gayahin',
    '許': 'payagan; pahintulutan',
    '融': 'matunaw; malusaw',
    '就': 'manungkulan; umupo sa puwesto',
    '勇': 'tapang; katapangan',
    '鮮': 'sariwa; malinaw',
    '審': 'pagdinig; husgahan; suriin',
    '燃': 'sumunog; mag-alab',
    '沈': 'lumubog; malumbay',
    '預': 'magdeposito; ipagkatiwala',
    '埋': 'ilibing; itabon',
    '虚': 'walang laman; kabulaanan',
    '剤': 'gamot; dosis',
    '荒': 'magaspang; bastos; ligalig',
    '熟': 'hinog; maging bihasa',
    '概': 'balangkas; sa pangkalahatan',
    '聖': 'banal; santo',
    '添': 'idagdag; samahan',
    '練': 'magsanay; hasain',
    '甘': 'matamis; layawin',
    '晴': 'maaraw; luminaw (ang panahon)',
    '庫': 'bodega; imbakan',
    '吸': 'sumipsip; huminga',
    '史': 'kasaysayan',
    '律': 'batas; ritmo',
    '則': 'patakaran; alituntunin',
    '丁': 'distrito; pambilang (panukat)',
    '怒': 'magalit; mainis',
    '騒': 'maingay; manggulo',
    '坊': 'batang lalaki; monghe',
    '滑': 'madulas; dumulas',
    '監': 'mangasiwa; bantayan',
    '既': 'dati na; noon pa',
    '香': 'insenso; bango',
    '測': 'sukatin; tantiyahin',
    '至': 'umabot; datnan',
    '尊': 'igalang; marangal',
    '援': 'tumulong; suportahan',
    '避': 'iwasan; umiwas',
    '幼': 'pagkabata; sanggol',
    '握': 'hawakan; kapitan',
    '誘': 'anyayahan; akitin',
    '浴': 'maligo; magpainit sa araw',
    '停': 'huminto; itigil',
    '宣': 'ipahayag; ideklara',
    '迫': 'pilitin; malapit nang mangyari',
    '蒸': 'pasingawan; alinsangan',
    '溶': 'matunaw',
    '揚': 'itaas; iprito',
    '兼': 'sabay na tungkulin; nang maaga',
    '裂': 'punitin; mahati',
    '棄': 'iwaksi; itapon',
    '威': 'takutin; karilagan',
    '還': 'ibalik; bumalik',
    '彩': 'kulay; pintura',
    '控': 'pigilin ang sarili; umiwas',
    '浄': 'linisin; dalisayin',
}
