# -*- coding: utf-8 -*-
"""
ja-kanji-advanced（上級漢字コース）の単字グロスのうち、既存3コースの単字見出しに
無かった字のタガログ語訳。kanji-tagalog-translate Workflow（翻訳→検証の2段パイプライン）
の出力から generate_manual_gloss.py で自動生成（手打ちではない）。
"""

MANUAL_GLOSS: dict[str, str] = {
    '取': 'kumuha; kunin',
    '付': 'dumikit; ikabit',
    '引': 'hilahin; banggitin',
    '定': 'magpasya; itakda',
    '当': 'tumama; nararapat',
    '化': 'magbago; maging',
    '込': 'masikip; kasali',
    '産': 'produkto; manganak',
    '成': 'maging; matupad',
    '務': 'tungkulin; trabaho',
    '受': 'tumanggap; sagutin',
    '感': 'damdamin; pakiramdam',
    '議': 'pulong; talakayan',
    '保': 'ingatan; panatilihin',
    '調': 'siyasatin; ihanda; himig',
    '打': 'hampasin; paluin',
    '連': 'isama; grupo',
    '最': 'pinaka-; higit sa lahat',
    '義': 'katarungan; kahulugan',
    '落': 'mahulog; bumagsak',
    '論': 'pangangatwiran; pagtatalo',
    '乗': 'sumakay; sumali',
    '官': 'opisyal; pamahalaan',
    '平': 'patag; kapayapaan',
    '交': 'makihalubilo; palitan',
    '記': 'isulat; talaan',
    '投': 'itapon; mamuhunan',
    '向': 'harapin; patungo sa',
    '進': 'sumulong; umunlad',
    '返': 'ibalik; sagutin',
    '配': 'ipamahagi; asawa',
    '過': 'sobra; lumampas',
    '解': 'unawain; kalasin',
    '好': 'gusto; magustuhan',
    '退': 'umatras; magretiro',
    '結': 'itali; magbuklod',
    '団': 'grupo; samahan',
    '然': 'gayon; talaga',
    '消': 'patayin; burahin',
    '放': 'palayain; ilabas',
    '算': 'magbilang; kalkulahin',
    '予': 'paunang; bago',
    '勝': 'manalo; tagumpay',
    '在': 'umiiral; matatagpuan',
    '満': 'puno; sapat',
    '収': 'kita; ipunin',
    '掛': 'isabit; umasa',
    '現': 'kasalukuyan; totoo',
    '士': 'propesyonal; mandirigma',
    '演': 'magtanghal; gumanap',
    '冷': 'malamig; palamigin',
    '失': 'mawala; pagkakamali',
    '速': 'mabilis; bilisan',
    '治': 'gumaling; mamahala',
    '伝': 'ipaabot; alamat',
    '寄': 'lumapit; mag-abuloy',
    '絶': 'putulin; lubos',
    '防': 'ipagtanggol; harangan',
    '養': 'alagaan; palakihin',
    '追': 'habulin; sundan',
    '価': 'halaga; presyo',
    '張': 'banatin; itayo',
    '路': 'daan; ruta',
    '給': 'sahod; ibigay',
    '老': 'matanda; tumanda',
    '資': 'puhunan; yaman',
    '減': 'kumulang; bumawas',
    '苦': 'paghihirap; pag-aalala',
    '告': 'sabihin; ipahayag',
    '限': 'limitasyon; hangganan',
    '検': 'suriin; siyasatin',
    '省': 'magnilay-nilay; ministri',
    '居': 'manirahan; naririto',
    '両': 'pareho; dalawa',
    '育': 'palakihin; lumaki',
    '続': 'ituloy; magpatuloy',
    '支': 'suportahan; sangay',
    '参': 'dumalo; sumali',
    '容': 'anyo; nilalaman; hitsura',
    '造': 'gumawa; likhain',
    '改': 'baguhin; ayusin',
    '応': 'sumagot; pumayag',
    '活': 'masigla; buhay',
    '増': 'dumami; dagdagan',
    '撃': 'atakihin; sumalakay',
    '営': 'magpatakbo ng negosyo; kampo',
    '接': 'makipag-ugnayan; dumikit',
    '師': 'guro; dalubhasa',
    '振': 'iwagayway; alugin',
    '散': 'kumalat; sabugin',
    '飛': 'lumipad; lumaktaw',
    '越': 'tumawid; lumagpas',
    '設': 'itatag; ihanda',
    '余': 'sobra; labis',
    '突': 'saksakin; biglaan',
    '殺': 'pumatay; puksain',
    '違': 'iba; kaiba',
    '洗': 'maghugas; linisin',
    '覚': 'tandaan; matuto; gumising',
    '渡': 'tumawid; ibigay; maghatid',
    '留': 'manatili; huminto; itigil',
    '異': 'iba; kakaiba',
    '視': 'tingnan; siyasatin; ituring',
    '示': 'ipakita; ituro',
    '置': 'ilagay; iwan; panatilihin',
    '降': 'bumaba; umulan; sumuko',
    '温': 'mainit-init; maligamgam',
    '盛': 'umunlad; sumikat; lumago',
    '修': 'mag-aral; sanayin; ayusin ang sarili',
    '衛': 'ipagtanggol; bantayan',
    '遺': 'ipamana; iwan',
    '短': 'maikli; kapintasan; kahinaan',
    '軽': 'magaan; hindi mahalaga',
    '細': 'manipis; makitid; detalyado',
    '辞': 'magbitiw; salita; termino',
    '果': 'bunga; matupad; matapos',
    '済': 'matapos; mabayaran; hindi na kailangan',
    '談': 'pag-usapan; kausapin',
    '競': 'makipagkumpitensya; makipagpaligsahan; magkarera',
    '婦': 'babae; asawang babae; babaing ikakasal',
    '護': 'protektahan; ipagsanggalang',
    '替': 'ipalit; kapalit; magpalit',
    '識': 'alamin; kilalanin; kaalaman',
    '領': 'teritoryo; nasasakupan',
    '装': 'magbihis; magkunwari',
    '処': 'asikasuhin; pangasiwaan; hatulan',
    '裁': 'humatol; magpasya; gupitin (tela)',
    '離': 'humiwalay; maghiwalay',
    '乱': 'kaguluhan; guluhin',
    '抜': 'bunutin; hugutin; alisin',
    '働': 'magtrabaho',
    '確': 'tiyakin; sigurado; matatag',
    '残': 'matira; natitira',
    '適': 'angkop; bagay; kwalipikado',
    '守': 'bantayan; ipagtanggol; sundin',
    '望': 'umasa; nais; hangarin',
    '隊': 'grupo; pangkat',
    '専': 'espesyalidad; eksklusibo; pangunahin',
    '圧': 'presyon; pigain; apihin',
    '遠': 'malayo',
    '勢': 'lakas; puwersa; sigla',
    '太': 'mataba; makapal',
    '締': 'higpitan; isara; itali',
    '認': 'kilalanin; aminin; paniwalaan',
    '査': 'imbestigahan; siyasatin',
    '健': 'malusog; malakas',
    '禁': 'ipagbawal; bawal',
    '挙': 'itaas; ihain; gawain',
    '低': 'mababa; mapagpakumbaba',
    '呼': 'tumawag; anyayahan',
    '除': 'alisin; ibukod; hatiin',
    '静': 'tahimik',
    '必': 'tiyak; siguradong mangyayari',
    '備': 'maghanda; ilaan; kagamitan',
    '払': 'magbayad; alisin',
    '射': 'bumaril; pumana; sumikat (liwanag)',
    '存': 'umiral; mayroon; ipagpalagay',
    '破': 'sirain; punitin; talunin',
    '清': 'malinis; linisin; dalisay',
    '達': 'makarating; maabot; matamo',
    '若': 'bata; baka (kung sakali)',
    '痛': 'masakit; sakit',
    '警': 'babalaan; kautusan',
    '準': 'semi-; katumbas; sumunod sa pamantayan',
    '深': 'malalim; palakasin',
    '規': 'pamantayan; tuntunin',
    '焼': 'ihawin; sunugin',
    '片': 'piraso; isang panig',
    '復': 'ibalik; bumalik; ipagpatuloy muli',
    '態': 'saloobin; kalagayan',
    '効': 'bisa; benepisyo; epekto',
    '疑': 'magduda; pagdudahan',
    '航': 'maglayag; lumipad',
    '材': 'materyales; kahoy; sangkap',
    '激': 'marahas; matindi; magalit nang husto',
    '栄': 'umunlad; karangalan; kaluwalhatian',
    '快': 'masaya; kaaya-aya; komportable',
    '縮': 'umurong; lumiit; kumupos',
    '暴': 'marahas; brutal; biglaang pagsabog ng galit',
    '押': 'itulak; pindutin; pigilan',
    '厚': 'makapal; mabait; magiliw',
    '察': 'hulaan; maunawaan; humatol',
    '敗': 'matalo; kabiguan',
    '倒': 'bumagsak; ibagsak; gumuho',
    '固': 'tumigas; mamuo; kumapal',
    '移': 'lumipat; ilipat',
    '換': 'ipalit; palitan; kumbertihin',
    '完': 'kumpleto; matapos',
    '協': 'makipagtulungan; sama-sama',
    '更': 'baguhin; higit pa; muli',
    '条': 'artikulo; sugnay; guhit',
    '補': 'dagdagan; punan; katulong',
    '免': 'patawarin; alisan ng pananagutan',
    '混': 'haluin; maghalo; malito',
    '浮': 'lumutang; pumaimbabaw',
    '構': 'itayo; bumuo; magkunwari',
    '遊': 'maglaro; magsaya; mamasyal',
    '登': 'umakyat; sumampa',
    '脱': 'maghubad; tumakas; makawala',
    '勤': 'magtrabaho; maglingkod; masipag',
    '争': 'makipagtalo; magkumpitensya; makipag-away',
    '険': 'mapanganib; matarik',
    '笑': 'tumawa; ngumiti',
    '障': 'hadlang; sagabal; balakid',
    '録': 'itala; talaan; rekord',
    '統': 'pamunuan; kaugnayan; kontrolin',
    '滅': 'mamatay; malipol; wasakin',
    '欠': 'kulang; kapintasan; hindi dumalo',
    '詰': 'siksikin; punuin; sisihin',
    '廃': 'alisin; ipawalang-bisa; itigil',
    '駆': 'tumakbo; sumugod; itaboy',
    '暗': 'madilim; kadiliman',
    '閉': 'isara; sarado',
    '介': 'mamagitan; tumulong; pamamagitan',
    '厳': 'mahigpit; istrikto; seryoso',
    '悲': 'malungkot; kalungkutan',
    '講': 'lektura; talakayin; asosasyon',
    '植': 'magtanim; itanim',
    '致': 'magdulot; magsanhi; gawin (magalang)',
    '企': 'magplano; balak; pagtatangka',
    '染': 'kulayan; magtina; mabahiran',
    '救': 'iligtas; sagipin; tulungan',
    '推': 'hulaan; ipalagay; irekomenda',
    '伸': 'umunat; humaba; lumago',
    '訴': 'magsakdal; umapela; magreklamo',
    '詞': 'salita; titik ng kanta',
    '継': 'ipagpatuloy; magmana; humalili',
    '皇': 'emperador',
    '称': 'tawag; titulo; papuri',
    '聴': 'makinig; pakinggan',
    '遅': 'mabagal; huli',
    '歴': 'kasaysayan; karanasan',
    '探': 'maghanap; hanapin',
    '典': 'alituntunin; batas; seremonya',
    '亡': 'yumao; namatay; patay na',
    '包': 'balutin; balot',
    '況': 'kalagayan; sitwasyon',
    '販': 'magbenta; ibenta',
    '府': 'pamahalaan; opisina ng gobyerno; prepektura',
    '域': 'rehiyon; saklaw; lawak',
    '提': 'magmungkahi; iharap; iprisenta',
    '爆': 'sumabog; bomba',
    '納': 'magbayad; itago; ihatid',
    '与': 'magbigay; ibigay; gawaran',
    '整': 'ayusin; maayos; ihanda',
    '属': 'kabilang; kasapi; sakop',
    '延': 'ipagpaliban; pahabain; palawigin',
    '創': 'lumikha; simulan; sugat',
    '司': 'mamahala; pinuno; opisyal',
    '即': 'agad; kaagad; ibig sabihin',
    '婚': 'kasal; pag-aasawa',
    '薄': 'manipis; malabnaw',
    '震': 'manginig; yumanig; lindol',
    '戻': 'bumalik; ibalik; isauli',
    '逃': 'tumakas; iwasan; tumalilis',
    '触': 'hipuin; dumampi; makipag-ugnayan',
    '訪': 'bumisita; dalawin',
    '似': 'kamukha; magkahawig; tumulad',
    '攻': 'sumalakay; umatake; punahin',
    '環': 'singsing; bilog; kadena',
    '責': 'sisihin; managot; pananagutan',
    '被': 'danasin; matamaan; sumailalim sa',
    '犯': 'krimen; gumawa ng krimen; kasalanan',
    '導': 'gabayan; pangunahan; giyahan',
    '標': 'marka; tanda; tunguhin',
    '互': "isa't isa; resiprokal; sabay-sabay",
    '求': 'humingi; hilingin; hanapin',
    '惑': 'malito; ligaligin; pagkalito',
    '築': 'magtayo; itayo; buuin',
    '恐': 'matakot; takot; kilabot',
    '請': 'humiling; makiusap; mag-imbita',
    '微': 'napakaliit; bahagya; banayad',
    '誤': 'mali; pagkakamali; magkamali',
    '華': 'kariktan; makinang; magarbo',
    '災': 'sakuna; kalamidad',
    '従': 'sumunod; sundin; tumalima',
    '占': 'sakupin; angkinin; manghula (ng kapalaran)',
    '遣': 'ipadala; magpadala',
    '照': 'magliwanag; ihambing; sumikat',
    '採': 'pumili; kumuha; mangalap',
    '刊': 'ilathala; maglathala',
    '闘': 'lumaban; away; digmaan',
    '償': 'magbayad-pinsala; bayaran; kabayaran',
    '宮': 'palasyo; dambana',
    '其': 'iyon; yaon',
    '授': 'magturo; ituro; gawaran',
    '辛': 'maanghang; mahirap tiisin',
    '汚': 'marumi; dumihan; kontaminado',
    '暖': 'mainit-init; init',
    '卒': 'magtapos (ng pag-aaral); sundalo',
    '季': 'panahon (ng taon)',
    '輸': 'ipadala; ihatid',
    '景': 'tanawin; eksena',
    '眠': 'matulog; antok',
    '捕': 'hulihin; dakpin',
    '担': 'pasanin; balikatin (responsibilidad)',
    '委': 'ipagkatiwala; komite',
    '均': 'pantay; katamtaman',
    '奏': 'tumugtog ng musika',
    '抗': 'lumaban; tumutol; sumalungat',
    '貴': 'mahalaga; marangal',
    '繰': 'balikan; ikutin; muling tingnan',
    '奇': 'kakaiba; kataka-taka',
    '診': 'magpasuri; suriin (ng doktor)',
    '層': 'saray; antas; palapag',
    '貨': 'kalakal; salapi',
    '敷': 'ilatag; ipatong',
    '執': 'hawakan; gampanan; isagawa',
    '葬': 'ilibing; libing',
    '序': 'paunang salita; pagkakasunod-sunod',
    '干': 'patuyuin; tumuyo',
    '却': 'sa halip; umatras',
    '閣': 'tore; palasyo',
    '託': 'ipagkatiwala; ipaubaya',
    '陣': 'kampo; hanay ng hukbo',
    '寒': 'malamig (panahon)',
    '危': 'mapanganib; delikado',
    '鳴': 'tumunog; humuni (ibon); tumahol (aso)',
    '易': 'madali; simple',
    '久': 'matagal na panahon',
    '祝': 'ipagdiwang; batiin',
    '慣': 'masanay; maging bihasa',
    '喜': 'matuwa; magalak',
    '迎': 'salubungin; batiin',
    '揺': 'umuga; yumanig',
    '飾': 'palamutihan; gayakan',
    '謝': 'humingi ng tawad; magpasalamat',
    '展': 'palawakin; ipakita (eksibit)',
    '覧': 'tingnan; basahin',
    '盗': 'magnakaw',
    '暮': 'takipsilim; mamuhay',
    '療': 'gamutin; pagalingin',
    '囲': 'palibutan; kulungin',
    '迷': 'maligaw; malito',
    '候': 'panahon; klima; hintayin',
    '模': 'tularan; gayahin',
    '許': 'payagan; pahintulutan',
    '融': 'matunaw; malusaw',
    '就': 'manungkulan; umupo sa puwesto',
    '勇': 'tapang; katapangan',
    '鮮': 'sariwa; malinaw',
    '審': 'pagdinig; husgahan; suriin',
    '燃': 'sumunog; mag-alab',
    '沈': 'lumubog; malumbay',
    '預': 'magdeposito; ipagkatiwala',
    '埋': 'ilibing; itabon',
    '虚': 'walang laman; kabulaanan',
    '剤': 'gamot; dosis',
    '荒': 'magaspang; bastos; ligalig',
    '熟': 'hinog; maging bihasa',
    '概': 'balangkas; sa pangkalahatan',
    '聖': 'banal; santo',
    '添': 'idagdag; samahan',
    '練': 'magsanay; hasain',
    '甘': 'matamis; layawin',
    '晴': 'maaraw; luminaw (ang panahon)',
    '庫': 'bodega; imbakan',
    '吸': 'sumipsip; huminga',
    '史': 'kasaysayan',
    '律': 'batas; ritmo',
    '則': 'patakaran; alituntunin',
    '丁': 'distrito; pambilang (panukat)',
    '怒': 'magalit; mainis',
    '騒': 'maingay; manggulo',
    '坊': 'batang lalaki; monghe',
    '滑': 'madulas; dumulas',
    '監': 'mangasiwa; bantayan',
    '既': 'dati na; noon pa',
    '香': 'insenso; bango',
    '測': 'sukatin; tantiyahin',
    '至': 'umabot; datnan',
    '尊': 'igalang; marangal',
    '援': 'tumulong; suportahan',
    '避': 'iwasan; umiwas',
    '幼': 'pagkabata; sanggol',
    '握': 'hawakan; kapitan',
    '誘': 'anyayahan; akitin',
    '浴': 'maligo; magpainit sa araw',
    '停': 'huminto; itigil',
    '宣': 'ipahayag; ideklara',
    '迫': 'pilitin; malapit nang mangyari',
    '蒸': 'pasingawan; alinsangan',
    '溶': 'matunaw',
    '揚': 'itaas; iprito',
    '兼': 'sabay na tungkulin; nang maaga',
    '裂': 'punitin; mahati',
    '棄': 'iwaksi; itapon',
    '威': 'takutin; karilagan',
    '還': 'ibalik; bumalik',
    '彩': 'kulay; pintura',
    '控': 'pigilin ang sarili; umiwas',
    '浄': 'linisin; dalisayin',
    '施': 'magsagawa; ipatupad; mag-alay ng tulong',
    '井': 'balon; poso (ng tubig)',
    '述': 'magsabi; ipahayag; banggitin',
    '武': 'mandirigma; militar; sandata',
    '欧': 'Europa',
    '含': 'maglaman; isama; kasama sa loob',
    '佐': 'katulong; pantulong (ranggo militar o pangalan)',
    '渉': 'tumawid; makialam; makipag-ugnayan (gaya sa negosasyon)',
    '響': 'umalingawngaw; tumunog; umabot sa damdamin',
    '討': 'lusubin; salakayin; talunin',
    '督': 'mangasiwa; pamunuan; mamahala',
    '催': 'magdaos; mag-organisa ng kaganapan',
    '及': 'umabot; makaapekto; hanggang sa',
    '憲': 'konstitusyon; batas',
    '摘': 'pumitas; ituro ang mali; ibuod',
    '批': 'pumuna; kritisismo; suriin',
    '郎': 'panlalaki na ginagamit sa mga pangalan ng lalaki (hal. Tarō); anak na lalaki',
    '央': 'gitna; sentro',
    '盟': 'alyansa; sumpaan; kasunduan',
    '捜': 'maghanap; magsiyasat',
    '拡': 'palawakin; palakihin; pahabain',
    '献': 'mag-alay; ambag; ihandog',
    '維': 'hibla; tali; lubid',
    '般': 'pangkalahatan; uri; lahat',
    '貿': 'kalakalan; pangangalakal',
    '邦': 'bansa; sariling bansa; Hapon',
    '緊': 'mahigpit; matindi; agaran',
    '昭': 'maningning; maliwanag (ginagamit sa mga pangalan, hal. Shōwa)',
    '頼': 'humiling; magtiwala; umasa sa iba',
    '僚': 'kasamahan sa trabaho; opisyal ng gobyerno',
    '吉': 'swerte; mapalad; kaligayahan',
    '臨': 'harapin; dumalo; humarap sa',
    '踏': 'tumapak; yapakan; tapakan',
    '署': 'pumirma; tanggapan ng pamahalaan; istasyon ng pulis',
    '壊': 'sirain; gibain; wasakin',
    '努': 'magsikap; magpursigi; pagsumikapan',
    '普': 'karaniwan; pangkalahatan; laganap',
    '康': 'kalusugan; kapayapaan',
    '豊': 'masagana; mainam; mayaman',
    '逮': 'arestuhin; hulihin',
    '承': 'pumayag; sumang-ayon; malaman at tanggapin',
    '崩': 'gumuho; matibag; masira',
    '紀': 'talaan ng kasaysayan; panahon; yugtong heolohiko',
    '博': 'doktor (Ph.D.); malawak ang kaalaman; ekspo',
    '患': 'magkasakit; magdusa sa sakit; pasyente',
    '絡': 'mapulupot; masangkot; magkakaugnay',
    '募': 'mangalap ng tao o donasyon; manghikayat sumali',
    '撤': 'umurong; bawiin; alisin',
    '削': 'tabasin; hasain; bawasan',
    '徒': 'naglalakad; mag-aaral; walang kabuluhan',
    '措': 'hakbang na gagawin; ilaan; itigil',
    '績': 'tagumpay; nagawa; resulta',
    '載': 'ilathala; itala; ikarga',
    '昇': 'umakyat; tumaas; mapataas sa ranggo',
    '抑': 'pigilin; sugpuin; supilin',
    '招': 'anyayahan; tawagin; imbitahan',
    '奈': 'ginagamit sa pangalan ng lugar (hal. Nara)',
    '困': 'malito; mahirapan; maabala',
    '永': 'walang hanggan; matagal; panghabang-buhay',
    '択': 'pumili; piliin',
    '秀': 'mahusay; natatangi; nangunguna',
    '徴': 'tanda; palatandaan; mangolekta',
    '誌': 'magasin; talaan; publikasyon',
    '功': 'tagumpay; nagawang mabuti; karangalan',
    '拠': 'batayan; saligan; himpilan',
    '秘': 'sikreto; itago; lihim',
    '拒': 'tumanggi; itakwil; hindi payagan',
    '抱': 'yakapin; kalungin; taglayin ang damdamin',
    '描': 'gumuhit; magpinta; ilarawan',
    '宇': 'kalawakan; sansinukob',
    '項': 'bagay-bagay; sugnay; talata',
    '伴': 'samahan; kasabay; kaakibat',
    '懸': 'mag-alala; nakasalalay; magsumikap',
    '巨': 'napakalaki; higante; malaki',
    '希': 'pag-asa; hangarin; bihira',
    '契': 'kasunduan; kontrata; pangako',
    '掲': 'ipaskil; ilathala; ipakita',
    '躍': 'lumukso; tumalon; umunlad nang aktibo',
    '邸': 'malaking bahay; mansyon',
    '依': 'umasa; sumandig; humiling ng tulong',
    '複': 'marami; maramihan; kopya',
    '慮': 'pag-isipan; alalahanin; mag-ingat',
    '郵': 'koreo; liham na ipinapadala',
    '恵': 'biyaya; pagpapala; kabaitan',
    '緩': 'luwagan; pagaanin; banayad',
    '需': 'pangangailangan; hinihingi ng merkado',
    '購': 'bumili; mag-suskribi',
    '揮': 'ipakita ang kakayahan; mamuno; iwagayway',
    '充': 'punuin; laanan; pagyamanin',
    '駐': 'pumarada; nakatalaga; manirahan pansamantala',
    '貢': 'mag-ambag; magbigay ng tulong',
    '鹿': 'usa',
    '賃': 'upa; sahod; bayad sa paggamit',
    '紹': 'ipakilala; magpakilala',
    '獲': 'makuha; magkamit; manghuli',
    '併': 'pagsamahin; pagsanibin; sabay',
    '徹': 'lubusan; hanggang wakas; magpuyat buong gabi',
    '衝': 'bumangga; banggaan; malakas na epekto',
    '焦': 'mabalisa; magmadali; masunog',
    '奪': 'agawin; nakawin nang dahas; angkinin sa puwersa',
    '雇': 'umempleyo; kumuha ng manggagawa; kontratahin',
    '析': 'suriin; pag-aralan nang detalyado; hatiin',
    '簡': 'simple; madali; maikli at tiyak',
    '譲': 'ibigay ang karapatan; isuko; ilipat sa iba',
    '樹': 'puno; kahoy; magtatag',
    '挑': 'hamunin; sumubok; makipagsapalaran',
    '紛': 'malito; mapagkamalan; mawala basta-basta',
    '促': 'udyukan; hikayatin; pilitin na kumilos',
    '慎': 'mag-ingat; maging maingat; mapagpakumbaba',
    '贈': 'magbigay ng regalo; iparangal; igawad',
    '智': 'karunungan; katalinuhan',
    '俊': 'henyo; matalino; natatangi',
    '渋': 'mapakla; mag-atubili; ayaw',
    '携': 'dalhin; dala-dala; bitbit',
    '撮': 'kumuha ng larawan; kumuha ng litrato',
    '誕': 'kapanganakan; ipinanganak; isilang',
    '侵': 'salakayin; lusubin; labagin',
    '括': 'itali; buklurin; higpitan',
    '到': 'pagdating; dumating; makarating',
    '透': 'malinaw; nakikita sa kabila; tumagos',
    '津': 'daungan; pantalan',
    '敏': 'matalas; maliksi; mabilis kumilos',
    '是': 'tama; wasto; katarungan',
    '排': 'itaboy; alisin; ihanay',
    '裕': 'masagana; sagana; mayaman',
    '賀': 'pagbati; batiin; kasiyahan',
    '扱': 'asikasuhin; hawakan; pangasiwaan',
    '顧': 'lumingon; balikan; suriin muli',
    '弘': 'malawak; malaki; masaklaw',
    '看': 'bantayan; alagaan; tingnan',
    '訟': 'idemanda; magsakdal',
    '戒': 'utos; babala; mag-ingat',
    '祉': 'kapakanan; kaligayahan',
    '誉': 'papuri; karangalan; katanyagan',
    '歓': 'kasiyahan; galak; tuwa',
    '勧': 'irekomenda; himukin; hikayatin',
    '翌': 'kasunod; sumunod na araw',
    '郷': 'sariling bayan; nayon; kinamulatang lugar',
    '敬': 'igalang; paggalang; pagpipitagan',
    '薦': 'irekomenda; imungkahi; ipayo',
    '悩': 'mag-alala; maligalig; mahirapan',
    '隠': 'itago; ikubli; takpan',
    '徳': 'kabutihan; birtud; mabuting asal',
    '哲': 'pilosopiya; karunungan; malinaw',
    '釈': 'paliwanag; ipaliwanag',
    '貯': 'ipunin; mag-ipon; itago',
    '妥': 'maamo; mapayapa; kasamaan',
    '熊': 'oso',
    '滞': 'maantala; matigil; mahuli',
    '隆': 'kaunlaran; kasaganaan; matayog',
    '暫': 'pansamantala; sandali; saglit',
    '忠': 'katapatan; katapatang-loob; lealtad',
    '倉': 'bodega; kamalig; imbakan',
    '彦': 'batang lalaki; ginoo (lumang salita, karaniwan sa pangalan)',
    '喚': 'sumigaw; tumawag; ipatawag',
    '沿': 'kahabaan (ng dalampasigan/ilog); sundan ang linya',
    '唱': 'awitin; bigkasin; ipahayag',
    '阿': 'manuyo; sumipsip; sulok',
    '索': 'lubid; maghanap; humanap',
    '忘': 'kalimutan; malimutan',
    '襲': 'salakayin; sumalakay; magmana (ng titulo)',
    '吹': 'umihip; hipan; hingahan',
    '懇': 'magiliw; taos-puso; mapagpatuloy',
    '俳': 'haiku; artista/aktor',
    '童': 'bata; kabataan',
    '驚': 'magulat; mabigla; mangilabot',
    '李': 'sirwelas; apelyidong Lee (Tsino o Koreano)',
    '浩': 'malawak; masagana; malakas',
    '陥': 'gumuho; mahulog (sa bitag); bumagsak (ang kuta)',
    '斎': 'paglilinis; pagsamba; silid (pang-relihiyon)',
    '慰': 'aliwin; aluin; ginhawahin',
    '賢': 'matalino; marunong; matalas ang isip',
    '舎': 'bahay; kubo; tuluyan',
    '較': 'ihambing; paghambingin',
    '覇': 'kapangyarihan; pamumuno; pagiging kampeon',
    '詳': 'detalyado; masusi; buong-buo',
    '抵': 'lumaban; sumalungat; abutin',
    '脅': 'takutin; pilitin; magbanta',
    '柔': 'malambot; banayad; mahinahon',
    '茂': 'lumago nang masagana; sumibol; siksik na tumubo',
    '犠': 'sakripisyo; ihandog',
    '距': 'distansya; layo',
    '雅': 'elegante; marikit; magara',
    '繁': 'masagana; siksikan; madalas',
    '濃': 'malapot; matindi (kulay); puro',
    '魅': 'akitin; mabighani; kaakit-akit',
    '斉': 'magkatulad; magkasabay; pantay',
    '貧': 'kahirapan; mahirap',
    '擁': 'yakapin; ipagtanggol; suportahan',
    '泳': 'lumangoy; languyin',
    '腐': 'mabulok; masira; manghina (ang loob)',
    '脚': 'binti; paa; ilalim/patungan',
    '尽': 'ubusin; gamitin lahat; magsilbi nang buong-buo',
    '孤': 'ulila; nag-iisa',
    '黄': 'dilaw',
    '賠': 'bayad-danyos; magbayad ng danyos',
    '頑': 'matigas ang ulo; matigas; determinado',
    '臣': 'opisyal ng hari; kawal ng hari; nasasakupan',
    '摩': 'kuskusin; hilutin; gilingin',
    '浅': 'mababaw; hindi malalim; balat-kayo',
    '励': 'himukin; palakasin ang loob; magsikap',
    '掃': 'magwalis; linisin',
    '掘': 'humukay; maghukay',
    '輝': 'kumislap; magniningning; sumikat',
    '蓄': 'mag-ipon; magtipon; itago',
    '巡': 'magpatrolya; umikot; libutin',
    '疲': 'mapagod; mapagal; manghina',
    '稼': 'kumita ng pera; magtrabaho',
    '瞬': 'kumurap; sandali; saglit',
    '捨': 'itapon; iwaksi; talikuran',
    '軟': 'malambot; hindi matigas',
    '噴': 'pumutok (bulkan); bumuga; sumabog',
    '誇': 'ipagmalaki; magyabang; ipagmayabang',
    '祥': 'mabuting tanda; kapalaran; suwerte',
    '牲': 'hayop na ihahandog; sakripisyo',
    '秩': 'kaayusan; pagkakasunud-sunod',
    '宏': 'maluwang; malaki; malawak',
    '唆': 'manuksó; mag-udyok; manghikayat (sa masama)',
    '阻': 'hadlangan; pigilan; harangin',
    '泰': 'mapayapa; kalmado; Thailand',
    '賄': 'suhol; suhulan; tustusan',
    '撲': 'sampalin; hampasin; bugbugin',
    '凍': 'mag-yelo; mamuo sa lamig; palamigin',
    '絞': 'sakalin; higpitan; pigain (parang basahan)',
    '膨': 'mamaga; lumaki; tumaba',
    '耐': 'matibay; matiisin; magtiis',
    '漏': 'tumagas; umagos palabas; mabunyag (sikreto)',
    '慶': 'pagdiriwang; batiin; magalak',
    '猛': 'mabangis; matindi; marahas',
    '芳': 'mabango; mabangong halimuyak',
    '懲': 'parusahan; disiplinahin',
    '郊': 'labas ng lungsod; nayon; suburbio',
    '踊': 'sumayaw; lumukso',
    '彰': 'malinaw; hayag; ipahayag',
    '棋': 'piyesa ng ahedres; shogi (ahedres ng Hapon)',
    '恒': 'palagian; permanente; walang hanggan',
    '冒': 'manganib; mangahas; lumaban sa panganib',
    '之': 'ng (klasikal); ito',
    '械': 'makinarya; kagamitan',
    '倫': 'moralidad; etika',
    '陳': 'ipakita; ilahad; ipaliwanag',
    '憶': 'alalahanin; gunitain',
    '怖': 'matakot; nakakatakot',
    '潜': 'sumisid; magtago; lumubog',
    '克': 'lampasan; daigin; malampasan (paghihirap)',
    '拘': 'arestuhin; huliin; maging partikular o mapili (sa mga detalye)',
    '黙': 'manahimik; tumigil sa pagsasalita',
    '須': 'kailangan talaga; dapat',
    '雰': 'kapaligiran (pakiramdam ng paligid); hamog',
    '遇': 'makasalubong; tratuhin; salubungin',
    '諮': 'kumunsulta; humingi ng payo',
    '狭': 'makipot; masikip',
    '喫': 'uminom; kumain; manigarilyo',
    '刷': 'limbagin; maglimbag; magpahid gamit ang brotsa',
    '糧': 'pagkain; probisyon; tustos',
    '簿': 'talaan; rehistro',
    '炉': 'pugon; hurno; reaktor',
    '牧': 'mag-alaga ng hayop; magpastol',
    '殊': 'lalo na; natatangi; espesyal',
    '殖': 'dumami; magparami; lumago',
    '輩': 'kasamahan; kapwa; grupo ng tao',
    '慢': 'mapanuya; tamad; pabaya',
    '謀': 'magbalak (ng masama); pakana; linlangin',
    '昌': 'maunlad; masagana',
    '拍': 'pumalakpak; ritmo ng tugtog',
    '朗': 'masayahin; malinaw; masigla',
    '鉱': 'mineral; bato mula sa mina',
    '寛': 'mapagparaya; mapagbigay; maluwag ang kalooban',
    '覆': 'tumaob; takpan; balutin',
    '胞': 'inunan; balot; kapatid (sa lahi)',
    '泣': 'umiyak; tumangis',
    '隔': 'paghiwalayin; ihiwalay; layuan',
    '貞': 'malinis ang asal; tapat; kalinisang-puri',
    '靖': 'mapayapa',
    '鑑': 'sanggunian; halimbawa; pag-aralan',
    '飼': 'mag-alaga ng hayop; pakainin',
    '銘': 'inskripsyon; tatak',
    '鋭': 'matalas; matulis; marahas',
    '随': 'sumunod; sumama; sundin',
    '烈': 'matindi; marahas; masidhi',
    '尋': 'magtanong; magsiyasat; hanapin',
    '丹': 'pula; taos-puso',
    '啓': 'ipahayag; buksan ang isip; ipaalam',
    '也': "ay (klasikal, katumbas ng 'to be')",
    '壌': 'lupa',
    '漫': 'komiks; hindi sinasadya; walang pigil (sa sarili)',
    '玄': 'misteryoso; malalim; itim',
    '粘': 'malagkit; magtiyaga',
    '悟': 'maunawaan; mapagtanto; magising-loob',
    '妊': 'pagbubuntis; buntis',
    '塗': 'pintahan; pahiran; palitadahan',
    '旭': 'sikat ng araw; umagang araw',
    '騰': 'tumaas; umakyat; lumundag',
    '往': 'paglalakbay; pumunta; noong una',
    '遂': 'tuparin; isakatuparan; matapos',
    '狂': 'baliw; sira ang ulo; nababaliw',
    '叫': 'sumigaw; humiyaw',
    '岐': 'sangahan ng daan; paghahati ng landas',
    '陛': 'kamahalan; kataas-taasan',
    '緯': 'latitud; pahalang na guhit',
    '培': 'linangin; alagaan; paunlarin',
    '衰': 'humina; manlata; bumagsak (kalusugan)',
    '艇': 'maliit na bangka; bangkang pansagwan',
    '屈': 'sumuko; yumuko; kumibot (sa takot)',
    '径': 'diyametro; daan; paraan',
    '淡': 'mahina (kulay); banayad; pansamantala',
    '抽': 'bunutin; hugutin; kunin (bahagi)',
    '披': 'ilantad; buksan; ihayag',
    '廷': 'hukuman; palasyo ng hari',
    '准': 'parang; kahalintulad; asosyado',
    '暑': 'mainit (panahon); alinsangan',
    '拝': 'sumamba; magdasal; igalang nang lubos',
    '奨': 'hikayatin; udyukan; palakasin ang loob',
    '浸': 'ibabad; isawsaw',
    '剰': 'labis; sobra',
    '胆': 'apdo; tapang; lakas ng loob',
    '繊': 'manipis; pino; hibla',
    '悔': 'magsisi; pagsisihan',
    '諭': 'sawayin; paalalahanan; hikayatin',
    '祈': 'manalangin; humiling',
    '惨': 'kalunos-lunos; nakakaawa; malupit',
    '虐': 'pahirapan; apihin',
    '翻': 'ibaligtad; iwagayway; baguhin (isip)',
    '墜': 'bumagsak; mahulog (mula sa taas)',
    '据': 'ilagay nang matatag; itayo; i-install',
    '徐': 'unti-unti; dahan-dahan',
    '搭': 'sumakay; ilulan; ikarga (sa sasakyan)',
    '忙': 'abala; walang panahon; hindi mapalagay',
    '拾': 'pumulot; mangolekta; sampu (sa opisyal na dokumento)',
    '軌': 'riles; landas; bakas ng gulong',
    '妨': 'hadlangan; abalahin; sagabal',
    '擦': 'kuskusin; ikiskis; gasgasin',
    '鯨': 'balyena',
    '荘': 'bahay-bakasyunan; malaking tirahan; marangal',
    '諾': 'pumayag; sumang-ayon',
    '漂': 'lumutang; maanod; padpad',
    '栽': 'pagtatanim; taniman',
    '拐': 'dumukot ng tao; manlinlang',
    '駄': 'walang kwenta; walang saysay; karga ng kabayo',
    '聡': 'matalino; mabilis matuto',
    '浪': 'gumala; alon; walang direksyon',
    '亜': 'Asya (maikling tawag); pangalawa sa ranggo; sub-',
    '詐': 'manloko; magsinungaling; mandaya',
    '勲': 'gawang kapuri-puri; medalya; karangalan',
    '酬': 'gantimpala; bayad; ganti',
    '湿': 'basa; halumigmig; mamasa-masa',
    '奮': 'masigla; maantig; sumigla',
    '逸': 'lumihis sa dapat; mawala; libangan',
    '涯': 'hangganan; dulo; abot-tanaw',
    '拓': 'linangin ang lupa; buksan para sa pagsasaka',
    '獄': 'bilangguan; piitan',
    '彫': 'mag-ukit; iskultura',
    '咲': 'mamulaklak; mamukadkad',
    '穏': 'payapa; tahimik; katamtaman',
    '顕': 'hayag; kitang-kita; lumitaw',
    '巧': 'magaling; bihasa; mahusay',
    '召': 'ipatawag; tawagin (magalang); isuot',
    '欺': 'linlangin; dayain',
    '隻': 'pambilang ng barko; isa sa magkapares',
    '粛': 'seryoso; taimtim; tahimik',
    '嘉': 'purihin; papurihan; mapalad',
    '遭': 'maranasan (ng masama); makaharap; magkasalubong',
    '架': 'itayo; estante; balangkas',
    '庶': 'karaniwang mamamayan; lahat',
    '稚': 'bata pa; hilaw; musmos',
    '滋': 'nakapagpapalakas; masustansya',
    '煮': 'pakuluan; lutuin',
    '誓': 'manumpa; mangako',
    '耕': 'magsaka; mag-araro; linangin ang lupa',
    '践': 'isagawa; ipatupad',
    '呈': 'ipakita; iharap; ihandog',
    '疎': 'malayo sa relasyon; iwasan; madalang',
    '仰': 'tumingala; igalang; umasa',
    '鈍': 'mapurol; mabagal umintindi; makapal ang ulo',
    '剛': 'matatag; malakas',
    '疾': 'mabilis; matulin; biglaan',
    '征': 'sakupin; lusubin; mangolekta ng buwis',
    '砕': 'durugin; basagin; dikdikin',
    '謙': 'mapagpakumbaba; magpakumbaba',
    '后': 'reyna; emperatriz; pagkatapos',
    '嘆': 'magbuntong-hininga; managhoy; magdalamhati',
    '頻': 'paulit-ulit; malimit',
    '潔': 'malinis; dalisay; marangal',
    '宰': 'mamuno; pangasiwaan',
    '廊': 'pasilyo; koridor',
    '伏': 'yumukod; humiga nang nakadapa; itago',
    '磨': 'kuskusin; pakintabin; sipilyuhin',
    '漠': 'malabo; hindi malinaw; disyerto',
    '晶': 'kristal; makintab; malinaw',
    '鎮': 'pakalmahin; patahimikin',
    '履': 'isuot sa paa; sapatos; tuparin',
    '劣': 'mas mababa ang kalidad; mas masama; hindi kasing galing',
    '那': 'ano? (lumang gamit); ginagamit sa pangalan ng lugar (hal. Naha)',
    '殴': 'suntukin; bugbugin; saktan',
    '娠': 'pagbubuntis; buntis',
    '奉': 'ihandog; maglingkod; italaga',
    '憂': 'malungkot; mag-alala; magdalamhati',
    '朴': 'simple; payak; walang kolorete',
    '亭': 'maliit na kubo; ginagamit sa pangalan ng restawran',
    '淳': 'dalisay; taos-puso (madalas gamit sa pangalan)',
    '怪': 'kaduda-duda; misteryoso; multo',
    '偉': 'dakila; kahanga-hanga; tanyag',
    '酔': 'lasing; nahihilo; nabighani',
    '惜': 'sayang; pagsisisi; maramot',
    '穫': 'anihin; ani',
    '佳': 'napakaganda; napakahusay; kaaya-aya',
    '潤': 'basain; kumita; magpaganda',
    '悼': 'ipagdalamhati; makiramay sa pagkamatay',
    '乏': 'kakulangan; kakaunti; limitado',
    '該': 'ang nasabing bagay; ang tinutukoy',
    '赴': 'pumunta sa bagong tungkulin; tumungo',
    '髄': 'utak-buto; kaibuturan; diwa',
    '晋': 'sumulong (lumang gamit); madalas gamit sa pangalan',
    '壮': 'malusog; malakas; kasibulan ng buhay',
    '飢': 'gutom; magutom',
    '傍': 'tagamasid; tabi; malapit',
    '疫': 'salot; epidemya',
    '累': 'maipon; masangkot; abala',
    '痴': 'hangal; tanga',
    '搬': 'dalhin; ilipat; ihatid',
    '晃': 'maliwanag; makinang (madalas gamit sa pangalan)',
    '癒': 'gumaling; pagalingin; mapawi ang uhaw',
    '寸': 'yunit ng sukat; kaunti lang',
    '郭': 'bakuran; kuta; pook-aliwan',
    '凶': 'masama; malas; kapahamakan',
    '吐': 'sumuka; dumura; magtapat',
    '賓': 'panauhing pandangal; bisita',
    '虜': 'bihag; bilanggo ng digmaan',
    '膚': 'balat; katawan',
    '陶': 'palayok; seramika',
    '憾': 'pagsisisi; panghihinayang',
    '紘': 'malaki (madalas gamit sa pangalan)',
    '磁': 'magnet; porselana',
    '弥': 'lalo pa; higit sa dati; unti-unting dumarami',
    '昆': 'insekto; nakatatandang kapatid; supling',
    '訂': 'baguhin; iwasto; ayusin',
    '庄': 'nayon; bukid; malaking sakahan',
    '敦': 'masipag; mabait; taos-puso',
    '騎': 'mangangabayo; sumakay sa kabayo',
    '寧': 'mas mabuti pa; payapa; tahimik',
    '濯': 'maglaba; hugasan; banlawan',
    '循': 'sumunod; ayon sa pagkakasunod-sunod',
    '忍': 'magtiis; magtiyaga; magtago; tiktik',
    '怠': 'pagpapabaya; katamaran',
    '如': 'katulad; parang; kagaya',
    '祐': 'tulong; tumulong',
    '鵬': 'higanteng ibon sa alamat; makapangyarihang ibon',
    '沸': 'kumulo; bumula; magalit nang husto',
    '珠': 'perlas; hiyas; alahas',
    '凝': 'mamuo; tumigas; mawili sa',
    '哀': 'kalungkutan; awa; pagdadalamhati',
    '跳': 'tumalon; lumukso',
    '菓': 'matamis; kendi; keyk',
    '垂': 'bumitin; lumaylay; sumabit',
    '蛇': 'ahas; lasenggo; matigas uminom ng alak',
    '澄': 'malinaw; luminaw; dalisay',
    '縫': 'manahi; magburda',
    '幾': 'ilan; gaano karami; kung ilan',
    '眺': 'tumingin; magmasid; tumanaw',
    '亘': 'sumaklaw; umabot; magpatuloy nang matagal',
    '呉': 'magbigay; gawin para sa iba; Kaharian ng Wu',
    '憩': 'magpahinga; pahinga',
    '媛': 'magandang babae; prinsesa',
    '恭': 'paggalang; magalang',
    '刈': 'gumapas; gupitin; putulin',
    '睡': 'antukin; matulog',
    '錯': 'malito; magulo; maghalu-halo',
    '帽': 'sombrero; takip sa ulo',
    '穀': 'butil; mga cereal (bigas, trigo)',
    '枯': 'malanta; matuyo; mamatay (tanim)',
    '弊': 'kasamaan; masamang gawi; pagkasira',
    '妃': 'reyna; prinsesa',
    '舶': 'barko; sasakyang-dagat',
    '餓': 'magutom nang matindi; nagugutom',
    '窮': 'maghirap; naipit; malito nang husto',
    '麗': 'maganda; magara; kaakit-akit',
    '綾': 'disenyong tela; makinis na sutla',
    '臭': 'mabaho; amoy; kahina-hinala',
    '悦': 'kaligayahan; galak',
    '縛': 'igapos; itali; pigilan',
    '宜': 'pagbati; mabuti; angkop',
    '辱': 'hiyain; ibaba ang dangal',
    '毅': 'matatag; malakas ang loob',
    '轄': 'kontrolin; pamahalaan',
    '稔': 'anihin; huminog',
    '窒': 'harangan; barahan; masakal',
    '炊': 'magluto; magsaing',
    '洪': 'baha; malawak',
    '摂': 'sumipsip; kumuha (sustansya); pumalit',
    '飽': 'mabusog; magsawa',
    '冗': 'labis; sobra; walang kwenta',
    '涼': 'presko; malamig na kaaya-aya',
    '狩': 'mangaso; manghuli',
    '紳': 'ginoo; maginoo',
    '枢': 'bisagra; sentro; pundasyon',
    '鍛': 'pandayin; sanayin nang husto; patatagin',
    '符': 'tanda; simbolo; anting-anting',
    '猶': 'gayunpaman; pa rin',
    '旋': 'umikot; paikot',
    '幣': 'salapi; pera; alay na papel (Shinto)',
    '憎': 'kamuhian; mapoot',
    '槽': 'tangke; batya',
    '慈': 'awa; kahabagan',
    '肯': 'pumayag; sumang-ayon',
    '楊': 'isang uri ng puno (willow)',
    '伐': 'putulin (puno); atakihin; parusahan',
    '駿': 'magandang kabayo; mabilis; matulin',
    '漬': 'ibabad; i-atsara',
    '燥': 'tumuyo; matuyo',
    '糾': 'imbestigahan; siyasatin; tanungin',
    '亮': 'malinaw; tumulong',
    '墳': 'libingan; puntod',
    '畜': 'hayop na inaalagaan; alagang hayop',
    '娯': 'libangan; aliw',
    '羅': 'manipis na sutla; ilatag; ayusin nang sunud-sunod',
    '峡': 'bangin; makipot na daanan sa bundok',
    '俸': 'sahod; suweldo',
    '圭': 'parisukat na hiyas; sulok; gilid',
    '醸': 'gumawa ng alak (magpaburo); maging sanhi',
    '弔': 'pakikiramay; pagluluksa; libing',
    '遍': 'saanman; paulit-ulit; malawakan',
    '衡': 'balanse; timbangan',
    '薫': 'mabango; humalimuyak',
    '羊': 'tupa',
    '款': 'mabuting kalooban; kasunduan; seksyon',
    '閲': 'suriin; siyasatin',
    '偵': 'espiya; tiktik',
    '喝': 'pagalitan; sigawan',
    '敢': 'matapang; buong-tapang; kaawa-awa',
    '胎': 'bahay-bata; sinapupunan',
    '酵': 'pagbuburo',
    '憤': 'magalit; magngitngit',
    '遮': 'harangan; hadlangan; putulin (usapan)',
    '硫': 'asupre',
    '赦': 'patawarin; kapatawaran',
    '挟': 'ipitin; nasa gitna',
    '窃': 'magnakaw; palihim',
    '瑞': 'mapalad na tanda; pagbati',
    '慨': 'magdalamhati; magbuntong-hininga',
    '紡': 'mag-ikid ng sinulid; gumawa ng sinulid',
    '恨': 'hinanakit; sama ng loob; magtanim ng galit',
    '肪': 'taba ng katawan',
    '扶': 'tumulong; umalalay; suportahan',
    '戯': 'maglaro; magbiro; kalokohan',
    '伍': 'hanay; pangkat ng lima; kasamahan (sa hukbo)',
    '忌': 'pagluluksa; kasuklam-suklam; taunang araw ng kamatayan',
    '濁': 'malabo; marumi; hindi malinaw (tunog)',
    '奔': 'tumakbo nang buong lakas; magmadali; sumugod',
    '迅': 'mabilis; matulin; agaran',
    '肖': 'kahawig; kamukha; magkatulad ang hitsura',
    '朽': 'mabulok; masira; malanta',
    '享': 'tamasahin; masiyahan; tanggapin',
    '秦': 'sinaunang dinastiyang Qin ng Tsina; ginagamit sa apelyido/pangalan',
    '茅': 'kugon; damong ginagamit sa pagtatayo ng bubong',
    '沙': 'buhangin',
    '輔': 'tumulong; umalalay; suportahan',
    '媒': 'tagapamagitan; tagapag-ugnay',
    '嘱': 'ipagkatiwala; hilingin; ipaalam',
    '迭': 'magpalitan; humalili; ipalit',
    '挿': 'ipasok; isaksak; ilagay sa loob',
    '椎': 'gulugod; buto ng likod',
    '陪': 'samahan; sumama bilang kasabay; umalalay (sa opisyal)',
    '剖': 'hatiin; hiwain (para siyasatin)',
    '譜': 'nota ng musika; talaangkanan; talaan',
    '郁': 'mabango; masagana at maganda (kultura)',
    '悠': 'matagal; walang hanggan; panatag at walang pagmamadali',
    '淑': 'marikit; magandang-asal; dalisay',
    '楠': 'puno ng kapur',
    '玲': 'malinaw at magandang tunog, gaya ng kalansing ng alahas',
    '翔': 'lumipad; pumaimbulog',
    '遷': 'lumipat; magbago; ilipat',
    '拙': 'walang kasanayan; kulang sa galing; pangit ang pagkakagawa',
    '篤': 'taos-puso; mabait; seryoso (lalo na sakit)',
    '肇': 'simula; pasimula',
    '渇': 'mauhaw; matuyo',
    '叔': 'tiyo (nakababatang kapatid ng magulang)',
    '亨': 'dumaloy nang maayos; maganda ang takbo',
    '堪': 'tiisin; magtiis; kayanin',
    '叙': 'isalaysay; ilarawan; ipagkaloob ng ranggo',
    '吟': 'umawit; bumigkas ng tula; kumatha',
    '逓': 'ipasa nang paisa-isa; ipadala sa bawat himpilan',
    '嶺': 'tuktok ng bundok',
    '甚': 'sobra; labis; matindi',
    '喬': 'mataas; mayabang',
    '崇': 'sambahin; igalang nang labis; dakilain',
    '愉': 'masaya; kasiyahan; matuwa',
    '礁': 'bahura; nakatagong bato sa dagat',
    '乃': 'kataga na katumbas ng "ng" (klasikal); kaya nga; mula sa',
    '洲': 'kontinente; pulo; buhanginan sa ilog',
    '屯': 'kampo; himpilan ng pulis; ton (timbang)',
    '樺': 'puno ng abedul; pulang-kayumanggi',
    '槙': 'palamuting punong laging-luntian; sanga',
    '姻': 'kasal; pag-aasawa',
    '巌': 'malaking bato; matarik na bato',
    '擬': 'gayahin; itutok (baril); iminungkahi bilang kandidato',
    '睦': "magkasundo; malapit sa isa't isa; maayos ang samahan",
    '閑': 'pahinga; walang ginagawa; tahimik',
    '胡': 'dayuhan; taga-ibang bansa (lumang tawag)',
    '幽': 'liblib; madilim; tahimik at malayo',
    '峻': 'matarik; napakataas',
    '曹': 'opisina ng gobyerno; kawani; kasamahan',
    '詠': 'bumigkas ng tula; kumatha; umawit',
    '卑': 'mababa; hamak; bastos',
    '侮': 'hamakin; insultuhin; walang halaga sa mata',
    '鋳': 'magbubo ng metal; hulmahin',
    '抹': 'burahin; pahiran; alisin',
    '槻': 'puno ng zelkova',
    '隷': 'alipin; utusan; bilanggo',
    '禍': 'kalamidad; kasawian; sumpa',
    '酪': 'gatas at produkto nito (keso, mantikilya)',
    '帥': 'kumander; pinuno ng hukbo',
    '逝': 'pumanaw; mamatay',
    '汽': 'singaw; usok mula sa tubig na kumukulo',
    '琢': 'kinisin; pakintabin (mamahaling bato)',
    '匿': 'itago; magtago; kublihan',
    '蕉': 'saging',
    '寡': 'balo; kaunti; iilan',
    '琉': 'mamahaling bato; ginagamit sa pangalan (Ryukyu)',
    '痢': 'pagtatae',
    '庸': 'karaniwan; pangkaraniwan; trabaho',
    '朋': 'kasama; kaibigan',
    '坑': 'hukay; minahan',
    '賊': 'magnanakaw; taksil; rebelde',
    '搾': 'pigain; piga',
    '畔': 'pilapil; gilid ng palayan o lawa',
    '遼': 'malayo',
    '唄': 'awit; kanta',
    '孔': 'butas; siwang',
    '漱': 'magmumog',
    '呂': 'gulugod (ginagamit din sa pangalan ng tao)',
    '拷': 'pahirapan; bugbugin',
    '苑': 'hardin; taniman; parke',
    '巽': 'timog-silangan (sa lumang direksyon)',
    '杜': 'kakahuyan; gubat',
    '渓': 'batis sa bundok; lambak',
    '廉': 'mura; tapat at malinis ang ugali',
    '謹': 'may paggalang; mapitagan; maingat magsalita',
    '湧': 'bumukal; sumibol; lumitaw nang bigla',
    '欣': 'matuwa; magalak',
    '褒': 'purihin; papurihan',
    '醜': 'pangit; kahiya-hiya; marumi ang kilos',
    '殉': 'magbuwis ng buhay para sa layunin; mamatay bilang martir',
    '煩': 'mag-alala; nakakabagabag; nakakainis',
    '禎': 'suwerte; mapalad; magandang kapalaran',
    '劾': 'akusahan; siyasatin nang opisyal',
    '堕': 'bumagsak sa masamang gawi; mahulog sa kasamaan',
    '租': 'buwis; upa; renta',
    '稜': 'sulok; gilid; taglay na kapangyarihan',
    '桟': 'harang ng pinto; tulos; muwelye',
    '倭': 'sinaunang Hapon; Yamato',
    '慕': 'mangulila (sa isang tao); sambahin; mahalin nang labis',
    '斐': 'maganda; may magandang disenyo',
    '罷': 'magbitiw; umalis sa puwesto; itigil',
    '矯': 'iwasto; ituwid; magpanggap',
    '囚': 'bilanggo; nahuli; ikulong',
    '魁': 'manguna sa iba; pangunahin',
    '鴻': 'malaking ibon (gansang-ligaw); dakila; makapangyarihan',
    '泌': 'tumagas; pumasok nang unti-unti; maglabas (glandula)',
    '赳': 'malakas at matapang',
    '漸': 'unti-unti; dahan-dahan; sa wakas',
    '葵': 'hollyhock (isang bulaklak)',
    '禄': 'sahod mula sa panginoon; pensyon; kaligayahan',
    '孟': 'pinuno; simula',
    '嫡': 'lehitimong asawa; tunay na inapo',
    '尭': 'mataas; malayo',
    '嚇': 'takutin; banta; taas-noo',
    '凸': 'matambok; hindi pantay',
    '暢': 'lumaganap; maluwag; umunlad nang maayos',
    '硝': 'asin-bato (ginagamit sa pulbura/salamin); nitrato',
    '勅': 'utos ng emperador',
    '芹': 'perehil (isang gulay); kamag-anak ng kintsay',
    '儒': 'Confucianismo; iskolar na Confucian',
    '鳳': 'alamat na ibong Phoenix (lalaki)',
    '馨': 'mabango; kaaya-aya',
    '慧': 'matalino; matalas ang isip',
    '愁': 'lungkot; pagdadalamhati; pagkabalisa',
    '楼': 'tore-bantayan; matayog na gusali',
    '彬': 'marangal; magalang',
    '匡': 'ituwid; iligtas; tumulong',
    '欽': 'igalang; hangaan; asamin',
    '褐': 'kayumanggi; kulay-tsokolate',
    '賜': 'ipagkaloob; kaloob mula sa nakatataas',
    '嵯': 'matarik; mabatong bundok',
    '綜': 'pagsamahin; buuin',
    '繕': 'tagpiin; ayusin; kumpunihin',
    '翠': 'luntian; salaksak (ibon)',
    '榛': 'avellana; punong avellana',
    '凹': 'malukong; may lubak',
    '伺': 'magtanong nang magalang; bumisita; mamanhik',
    '惣': 'lahat; kabuuan',
    '蔦': 'baging; halamang gumapang',
    '錬': 'hasain (metal); sanayin; paghusayin',
    '衷': 'kaibuturan ng puso; tapat na damdamin',
    '逐': 'habulin; itaboy; tuparin',
    '斥': 'tanggihan; itaboy; umatras',
    '芙': 'loto (bulaklak); may kaugnayan sa Bundok Fuji',
    '皐': 'latian; pampang',
    '惟': 'isipin; pag-isipan; magnilay',
    '佑': 'tumulong; tulong',
    '耀': 'kumintab; kumikislap; magningning',
    '黛': 'pangkulay ng kilay; kilay na pinaitim',
    '渥': 'kagandahang-loob; basain',
    '憧': 'mangarap; asamin; hangaan',
    '妄': 'maling akala; walang basehan; padalus-dalos',
    '惇': 'tapat; mabait; maalalahanin',
    '脩': 'tuyong karne',
    '甫': 'sa wakas; ngayon lang; unang pagkakataon',
    '酌': 'magsilbi ng alak; sumandok ng tubig',
    '嬉': 'masaya; natutuwa',
    '蒼': 'asul; maputla',
    '暉': 'sinag; liwanag',
    '頒': 'ipamahagi; ikalat',
    '肢': "paa't kamay; galamay",
    '檀': 'kahoy na mabango (sandalo); sedro',
    '凱': 'awit ng tagumpay; pagdiriwang ng panalo',
    '彗': 'kometa',
    '謄': 'kopyahin; magparami ng kopya',
    '梓': 'punong catalpa; paglilimbag gamit ang tablang kahoy',
    '嗣': 'tagapagmana; humalili',
    '叶': 'matupad; pagbigyan',
    '汐': 'agos ng dagat; tubig-alat; pagkakataon',
    '絢': 'makulay na disenyo; makinang',
    '朔': 'unang araw ng buwan; bagong buwan; hilaga',
    '伽': 'mag-alaga; kasamang panlibang',
    '抄': 'sipi; buod; kopya',
    '爽': 'nakakaginhawa; sariwa; malinaw',
    '黎': 'madilim bago magbukang-liwayway; marami',
    '惰': 'tamad; katamaran',
    '蛮': 'barbaro; walang-modo',
    '冴': 'malinaw; mahusay; malamig',
    '旺': 'umuunlad; masigla; matagumpay',
    '萌': 'sumibol; usbong',
    '偲': 'alalahanin; gunitain',
    '壱': 'isa (sa opisyal na dokumento)',
    '瑠': 'lapis lazuli (mamahaling bato)',
    '允': 'pumayag; pahintulutan; katapatan',
    '蒔': 'maghasik ng buto',
    '弧': 'arko; kurba',
    '遥': 'malayo; noong unang panahon',
    '舜': 'hibiskus (uri ng bulaklak)',
    '瑛': 'kislap ng hiyas; kristal',
    '附': 'idugtong; ikabit; isama',
    '彪': 'batik-batik; munting tigre',
    '但': 'ngunit; subalit',
    '綺': 'makulay na tela; maganda',
    '茜': 'pulang-pula (mula sa halamang madder)',
    '凌': 'makayanan; malagpasan; hamunin',
    '皓': 'puti; malinaw',
    '洸': 'kumikislap na tubig',
    '毬': 'bola; matinik na balat (kastanyas)',
    '婆': 'matandang babae; lola; yaya',
    '緋': 'pulang-matingkad',
    '怜': 'matalino',
    '邑': 'nayon; bayan',
    '倣': 'gayahin; tularan',
    '碧': 'asul-berde; kulay-jade',
    '啄': 'tumuka; dumukot ng pagkain (gaya ng ibon)',
    '穣': 'masaganang ani; kasaganaan',
    '悌': 'paggalang at pagmamahal sa nakatatanda; pagiging mabuting kapatid',
    '倹': 'matipid; magtipid; pagtitipid',
    '柚': 'yuzu (uri ng citrus)',
    '伎': "kasanayan; galing (ginagamit sa salitang 'kabuki')",
    '瞭': 'malinaw; maliwanag',
    '颯': 'malakas na ihip ng hangin; biglaan at mabilis',
    '諒': 'unawain; tanggapin nang may pag-unawa',
    '莉': "sampagita (ginagamit sa pangalan, gaya ng '茉莉')",
    '且': 'bukod pa rito; higit pa; saka',
    '栞': 'pananda ng pahina; gabay sa paglalakbay',
    '旦': 'bukang-liwayway; umaga',
    '楓': 'puno ng maple',
    '璃': 'kristal; mamahaling asul na bato (lapis lazuli)',
    '汰': 'salain; piliin at tanggalin ang di-kailangan; karangyaan',
    '胤': 'inapo; supling; angkan',
    '叡': 'matalino; pang-emperador',
    '謁': 'pagharap sa hari o emperador; audiensya',
    '箇': "pambilang ng bagay (parang 'piraso')",
    '茄': 'talong',
    '侃': 'matatag; makatarungan; mapayapa',
    '莞': 'ngumiti; tambo na ginagamit sa paggawa ng banig (tatami)',
    '誼': 'pagkakaibigan; matalik na relasyon',
    '斤': 'palakol; kati (yunit ng bigat); pambilang ng tinapay',
    '衿': 'kwelyo; leeg ng damit',
    '玖': 'magandang itim na bato; siyam (pormal na paraan ng pagsulat ng bilang)',
    '虞': 'pangamba; kaba; posibilidad ng masamang mangyari',
    '袈': "kasuutan ng monghe (ginagamit sa salitang '袈裟')",
    '絃': 'kwerdas ng instrumentong pangmusika; tali',
    '梧': 'puno ng Phoenix; punong payong ng Tsina',
    '瑚': 'koral',
    '倖': 'kaligayahan; suwerte',
    '昂': 'tumaas; umangat; pumataas ang loob',
    '墾': 'magbungkal ng lupa; gawing sakahan',
    '瑳': 'makinang na puting kislap ng hiyas; pino at maganda',
    '裟': "kasuutan ng monghe (ginagamit sa salitang '袈裟')",
    '采': 'dado; anyo o hitsura; kumuha o tipunin',
    '燦': 'makinang; nagniningning',
    '爾': 'ikaw (lumang panghalip, pormal/klasikal)',
    '紗': 'manipis na tela; gasa',
    '勺': 'sandok; maliit na yunit ng dami ng likido',
    '爵': 'titulo ng maharlika (baron); ranggo sa hukuman',
    '竣': 'matapos; makumpleto (lalo na sa konstruksiyon)',
    '遵': 'sumunod; sundin ang batas o tuntunin',
    '恕': 'patawarin; pagpaumanhinan; maunawain',
    '捷': 'tagumpay; pananalo; mabilis',
    '菖': "iris (bulaklak, ginagamit sa salitang '菖蒲')",
    '丞': 'tumulong; katulong na opisyal',
    '錘': 'timbang; plomada; ikiran sa paghabi',
    '嵩': 'dumami; lumaki ang bulto; tumaas ang dami',
    '碩': 'malaki; dakila; kilalang-kilala',
    '銑': 'hilaw na bakal',
    '塑': 'hulmahin; hubugin, gaya sa eskultura',
    '脹': 'mamaga; lumaki; bumukol',
    '朕': 'ako (panghalip na ginagamit ng emperador)',
    '紬': 'uri ng magaspang na seda (tsumugi)',
    '痘': 'bulutong (sakit sa balat)',
    '凪': 'katahimikan ng dagat; kalmado, walang alon o hangin',
    '捺': 'idiin ang selyo; tumatak',
    '弐': 'dalawa (pormal na paraan ng pagsulat ng bilang)',
    '柊': 'holly (uri ng halaman)',
    '賦': 'buwis; tula o taludtod; hulugan sa pagbabayad',
    '蕗': 'fuki (uri ng gulay/halaman)',
    '柾': 'tuwid na hibla ng kahoy; uri ng punong spindle',
    '亦': 'din; naman; muli',
    '麿': 'ako o ikaw (lumang panghalip, madalas sa pangalan)',
    '椋': 'uri ng punong lumalagas ang dahon; ibong kulay-abo',
    '耗': 'bumaba; maubos; kumonti',
    '匁': 'monme (lumang yunit ng timbang, 3.75 gramo)',
    '冶': 'pagtunaw ng metal; paghuhulma',
    '耶': 'tandang pananong (ginagamit sa lumang panitikan)',
    '宥': 'pakalmahin; patahimikin; pahupain',
    '蓉': "loto (tulad sa salitang '芙蓉')",
    '濫': 'labis; umapaw; kumalat nang walang kontrol',
    '吏': 'opisyal ng gobyerno',
    '琳': 'hiyas; tunog ng kalansing ng alahas',
    '麟': 'kirin (alamat na hayop); henyo; girafa',
    '伶': 'aktor; manunugtog (klasikal na termino)',
    '侑': 'anyayahan kumain; alukin ng pagkain',
    '勁': 'malakas; matatag',
    '奎': 'bituin; diyos ng panitikan',
    '崚': 'hanay ng matataas at matarik na bundok',
    '昴': "Pleiades, kumpol ng bituin (tinatawag ding 'Subaru')",
    '晏': 'huli; tahimik; paglubog ng araw',
    '晨': 'umaga; maagang oras',
    '晟': 'malinaw; maliwanag',
    '椰': 'puno ng niyog',
    '洵': 'tunay; totoo',
    '滉': 'malalim at malawak, gaya ng dagat o ilog',
    '澪': 'daanan ng barko sa dagat o ilog; agusan ng tubig',
    '燎': 'apoy; siga',
    '燿': 'kumintab; nagniningning',
    '瑶': 'maganda parang hiyas',
    '眸': 'balintataw ng mata',
    '笙': 'shō, instrumentong pangmusikang may mga tambo',
    '綸': 'sinulid; telang seda',
    '茉': "sampagita (ginagamit sa salitang '茉莉')",
    '菫': 'violeta (uri ng bulaklak)',
    '詢': 'kumunsulta; humingi ng opinyon',
    '諄': 'paulit-ulit at mahaba sa pagsasalita; nakakasawa',
    '迪': 'patnubayan; daan; landas',
    '頌': 'papuri; awit ng pagpupuri',
    '凜': 'matinding lamig; mahigpit; disiplinado ang dating',
    '熙': 'maliwanag; maunlad; masagana',
}
